In [676]:
import pandas as pd
import numpy as np

<!-- Read data file -->

## Read data file

In [677]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [678]:
working_path = "/content/drive/My Drive/HCMUS/Intro2DS/Lab/Lab02/"

In [679]:
df = pd.read_csv(working_path + 'lab_02.csv')

In [680]:
df

,Order_ID,Order_Date,Order_Priority,Customer_ID,Customer_Name,Industry_name,Customer_Segment,Province,Region,Channel,...,Product_Category,Product_Sub-Category,Product_Name,Sales,Quantity,Unit_Price,Discount,Profit,Returned_Reason,Age_Group
0,HC-2011-103800,1/4/24,Medium,DP-13000,Darren Tran,Thiết bị gia dụng,Consumer,Hồ Chí Minh,Miền Đông Nam Bộ,Store,...,Hàng điện lạnh,Tủ lạnh,"Message Book, Wirebound, Four 5 1/2"" X 4"" Form...",16.448,2.0,8.224,0.2,5.5512,No reason,>=55
1,NA-2011-112326,2024.01.05,Medium,PO-19195,Phillina Ober,Thiết bị gia dụng,Home Office,Nghệ An,Miền Trung,Online,...,Hàng điện lạnh,Máy điều hòa,MÁY LẠNH DAIKIN FTKC60NVMV-BBB,11.784,3.0,3.928,0.2,4.2717,"""""",35-44
2,NA-2011-112326,1/5/24,Low,PO-19195,Phillina Ober,Thiết bị gia dụng,Home Office,Nghệ An,Miền Trung,Online,...,Hàng điện lạnh,Máy điều hòa,MÁY LẠNH LG V13BPB,272.736,3.0,90.912,0.2,-64.7748,"""""",>=55
3,NA-2011-112326,1/5/24,Low,PO-19195,Phillina Ober,Thiết bị gia dụng,Home Office,Nghệ An,Miền Đông Nam Bộ,Online,...,Hàng điện lạnh,Máy giặt,GBC Standard Plastic Binding Systems Combs,3.540,2.0,NaN,0.8,-5.4870,NaN,45
4,TN-2011-141817,1/6/24,Medium,MB-18085,Trần Nhiễm,Thiết bị gia dụng,Consumer,Tây Ninh,Miền Đông Nam Bộ,Store,...,Hàng điện lạnh,Máy giặt,Avery Hi-Liter EverBold Pen Style Fluorescent ...,19.536,3.0,6.512,0.2,4.8840,NaN,25-34
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
498,HT-2011-127166,5/21/24,Medium,KH-16360,Trần Đức,Thiết bị gia dụng,Consumer,Hà Tỉnh,Miền Trung,Agent,...,Hàng điện lạnh,Tủ lạnh,"Adams Telephone Message Books, 5 1/4” x 11”",4.832,1.0,4.832,0.2,1.6308,NaN,>=55
499,HT-2011-127166,5/21/24,Low,KH-16360,Trần Đức,Thiết bị gia dụng,Consumer,Hà Tỉnh,Miền Trung,Agent,...,Hàng điện lạnh,Máy giặt,Ibico Plastic Spiral Binding Combs,18.240,3.0,6.080,0.8,-31.0080,NaN,>=55
500,HT-2011-127166,5/21/24,Low,KH-16360,Trần Đức,Thiết bị gia dụng,Consumer,Hà Tỉnh,Miền Trung,Agent,...,Hàng điện lạnh,Máy giặt,Ibico Plastic Spiral Binding Combs,18.240,3.0,6.080,0.8,-31.0080,NaN,>=55
501,HC-2011-130673,5/20/24,Low,MC-17590,Nguyễn Thị Thu Hường,Thiết bị gia dụng,Corporate,Hồ Chí Minh,Miền Đông Nam Bộ,Agent,...,Hàng điện lạnh,Máy điều hòa,Rogers Profile Extra Capacity Máy điều hòa Tub,66.960,5.0,13.392,0.2,-13.3920,NaN,25-34
502,HC-2011-113768,5/13/24,Medium,AH-10030,Trương Thanh Vân,Thiết bị gia dụng,Corporate,Hồ Chí Minh,Miền Đông Nam Bộ,Agent,...,Nội thất,Ghế,"Iceberg Nesting Folding Chair, 19w x 6d x 43h",279.456,6.0,46.576,0.2,20.9592,NaN,18-24

In [681]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 503 entries, 0 to 502
Data columns (total 21 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   Order_ID              503 non-null    object
 1   Order_Date            503 non-null    object
 2   Order_Priority        502 non-null    object
 3   Customer_ID           502 non-null    object
 4   Customer_Name         503 non-null    object
 5   Industry_name         502 non-null    object
 6   Customer_Segment      500 non-null    object
 7   Province              500 non-null    object
 8   Region                498 non-null    object
 9   Channel               500 non-null    object
 10  Product_ID            500 non-null    object
 11  Product_Category      500 non-null    object
 12  Product_Sub-Category  500 non-null    object
 13  Product_Name          500 non-null    object
 14  Sales                 500 non-null    float64
 15  Quantity              500 non-null    float64
 16  Unit_Price            496 non-null    float64
 17  Discount              480 non-null    float64
 18  Profit                500 non-null    float64
 19  Returned_Reason       10 non-null     object
 20  Age_Group             503 non-null    object
dtypes: float64(5), object(16)
memory usage: 82.7+ KB

In [682]:
df.describe()

              Sales    Quantity   Unit_Price    Discount       Profit
count    500.000000  500.000000   496.000000  480.000000   500.000000
mean     234.264846    3.760000    58.221347    0.149479    18.155669
std     1082.351129    2.284039   187.532751    0.200534   137.217015
min     -391.980000   -4.000000     0.360000   -0.100000 -1811.078400
25%       16.640000    2.000000     5.184000    0.000000     2.277250
50%       46.832000    3.000000    13.392000    0.150000     7.370000
75%      168.537500    5.000000    55.480000    0.200000    23.951600
max    22638.480000   14.000000  3773.080000    0.800000  1276.487100

## Data preprocessing

### Data quality
*   Accuracy
*   Completeness
*   Consistency
*   Timeliness
*   Validity
*   Uniqueness

In [683]:
df_copy = df.copy()

## 1. Completeness

*   Missing data
*   Empty Strings
*   Missing Rows

#### Step by step:
Step 1: List of columns need to check: Customer_ID, Industry_name, Customer_Segment, Province, Region, Channel, Product_ID, Product_Category, Product_Sub_category, Product_Name, Sales, Quantity, Unit_Price, Discount, Profit

Step 2: Check missing data and handling missing value for categorical colums


*   Check missing data of each column:  **dataframe[dataframe['Column_name'].isna()]**
*   Handling missing values: remove/ replace by valid value

Step 3: Check missing data and handling missing value for numerical columns
*   Check missing data of each column:  **dataframe[dataframe['Column_name'].isna()]**
*   Handling missing values: remove/ replace by valid value or a calculation

In [684]:
# 1. Completeness: Checking and handling missing data
# Count missing values per column
df_copy.isnull().sum()

Order_ID                  0
Order_Date                0
Order_Priority            1
Customer_ID               1
Customer_Name             0
Industry_name             1
Customer_Segment          3
Province                  3
Region                    5
Channel                   3
Product_ID                3
Product_Category          3
Product_Sub-Category      3
Product_Name              3
Sales                     3
Quantity                  3
Unit_Price                7
Discount                 23
Profit                    3
Returned_Reason         493
Age_Group                 0
dtype: int64

In [685]:
# 1. Completeness: Checking and handling missing data
# Show NAN Rows
df_copy[df_copy.isna().any(axis=1)]

,Order_ID,Order_Date,Order_Priority,Customer_ID,Customer_Name,Industry_name,Customer_Segment,Province,Region,Channel,...,Product_Category,Product_Sub-Category,Product_Name,Sales,Quantity,Unit_Price,Discount,Profit,Returned_Reason,Age_Group
3,NA-2011-112326,1/5/24,Low,PO-19195,Phillina Ober,Thiết bị gia dụng,Home Office,Nghệ An,Miền Đông Nam Bộ,Online,...,Hàng điện lạnh,Máy giặt,GBC Standard Plastic Binding Systems Combs,3.540,2.0,NaN,0.8,-5.4870,NaN,45
4,TN-2011-141817,1/6/24,Medium,MB-18085,Trần Nhiễm,Thiết bị gia dụng,Consumer,Tây Ninh,Miền Đông Nam Bộ,Store,...,Hàng điện lạnh,Máy giặt,Avery Hi-Liter EverBold Pen Style Fluorescent ...,19.536,3.0,6.512,0.2,4.8840,NaN,25-34
5,ĐN-2011-130813,1/7/24,Medium,LS-17230,Lycoris Saunders,Thiết bị gia dụng,Consumer,Đồng Nai,Miền Đông Nam Bộ,Store,...,Hàng điện lạnh,Tủ lạnh,Xerox 225,19.440,3.0,6.480,0.0,9.3312,NaN,35-44
6,HC-2011-106054,1/7/24,Medium,JO-15145,Jack O'Briant,Thiết bị gia dụng,Corporate,Hồ Chí Minh,Miền Đông Nam Bộ,Online,...,Hàng điện lạnh,Máy giặt,"Dixon Prang Watercolor Pencils, 10-Color Set w...",12.780,3.0,4.260,NaN,5.2398,NaN,>=55
7,HN-2011-167199,1/7/24,High,ME-17320,Nguyễn Ca Hùng,Thiết bị gia dụng,Home Office,Hà Nội,Miền Bắc,Online,...,Nội thất,Ghế,Ghế làm việc 2MV2506-M1,2573.820,9.0,285.980,NaN,746.4078,NaN,35-44
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
498,HT-2011-127166,5/21/24,Medium,KH-16360,Trần Đức,Thiết bị gia dụng,Consumer,Hà Tỉnh,Miền Trung,Agent,...,Hàng điện lạnh,Tủ lạnh,"Adams Telephone Message Books, 5 1/4” x 11”",4.832,1.0,4.832,0.2,1.6308,NaN,>=55
499,HT-2011-127166,5/21/24,Low,KH-16360,Trần Đức,Thiết bị gia dụng,Consumer,Hà Tỉnh,Miền Trung,Agent,...,Hàng điện lạnh,Máy giặt,Ibico Plastic Spiral Binding Combs,18.240,3.0,6.080,0.8,-31.0080,NaN,>=55
500,HT-2011-127166,5/21/24,Low,KH-16360,Trần Đức,Thiết bị gia dụng,Consumer,Hà Tỉnh,Miền Trung,Agent,...,Hàng điện lạnh,Máy giặt,Ibico Plastic Spiral Binding Combs,18.240,3.0,6.080,0.8,-31.0080,NaN,>=55
501,HC-2011-130673,5/20/24,Low,MC-17590,Nguyễn Thị Thu Hường,Thiết bị gia dụng,Corporate,Hồ Chí Minh,Miền Đông Nam Bộ,Agent,...,Hàng điện lạnh,Máy điều hòa,Rogers Profile Extra Capacity Máy điều hòa Tub,66.960,5.0,13.392,0.2,-13.3920,NaN,25-34
502,HC-2011-113768,5/13/24,Medium,AH-10030,Trương Thanh Vân,Thiết bị gia dụng,Corporate,Hồ Chí Minh,Miền Đông Nam Bộ,Agent,...,Nội thất,Ghế,"Iceberg Nesting Folding Chair, 19w x 6d x 43h",279.456,6.0,46.576,0.2,20.9592,NaN,18-24

In [686]:
# 1. Completeness: Checking and handling missing data
# 1.1 Check each column: Customer_ID
df_copy[df_copy['Customer_ID'].isna()]

,Order_ID,Order_Date,Order_Priority,Customer_ID,Customer_Name,Industry_name,Customer_Segment,Province,Region,Channel,...,Product_Category,Product_Sub-Category,Product_Name,Sales,Quantity,Unit_Price,Discount,Profit,Returned_Reason,Age_Group
493,VP-2011-152443,5/21/24,NaN,NaN,Trà Ngọc Hằng,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,25-34

In [687]:
# 1. Completeness: Checking and handling missing data
# 1.1 Check each column: Customer_ID --> Tất cả các giá trị ở dòng có chứa Customer_ID = NA ==> Remove dòng này luôn
df_copy = df_copy.drop(df_copy[df_copy['Order_ID'] == 'VP-2011-152443'].index)
## double check after dropping
df_copy[df_copy['Customer_ID'].isna()]

Empty DataFrame
Columns: [Order_ID, Order_Date, Order_Priority, Customer_ID, Customer_Name, Industry_name, Customer_Segment, Province, Region, Channel, Product_ID, Product_Category, Product_Sub-Category, Product_Name, Sales, Quantity, Unit_Price, Discount, Profit, Returned_Reason, Age_Group]
Index: []

[0 rows x 21 columns]

In [688]:
# 1. Completeness: Checking and handling missing data
# 1.2 Check each column: Industry_name, Order_Priority
df_copy[df_copy['Industry_name'].isna()]
df_copy[df_copy['Order_Priority'].isna()]

Empty DataFrame
Columns: [Order_ID, Order_Date, Order_Priority, Customer_ID, Customer_Name, Industry_name, Customer_Segment, Province, Region, Channel, Product_ID, Product_Category, Product_Sub-Category, Product_Name, Sales, Quantity, Unit_Price, Discount, Profit, Returned_Reason, Age_Group]
Index: []

[0 rows x 21 columns]

In [689]:
# 1. Completeness: Checking and handling missing data
# 1.3 Check each column: Customer_Segment
df_copy[df_copy['Customer_Segment'].isna()]

,Order_ID,Order_Date,Order_Priority,Customer_ID,Customer_Name,Industry_name,Customer_Segment,Province,Region,Channel,...,Product_Category,Product_Sub-Category,Product_Name,Sales,Quantity,Unit_Price,Discount,Profit,Returned_Reason,Age_Group
147,ĐN-2011-105648,3/3/24,Low,EJ-14155,Eva Jacobs,Thiết bị gia dụng,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,25-34
165,HC-2011-140116,3/10/24,Medium,KT-16480,Bùi Công Danh,Thiết bị gia dụng,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,18-24

In [690]:
# 1. Completeness: Checking and handling missing data
# 1.3 Check each column: Customer_Segment --> Check and review carefully data rows before dropping
df_copy[df_copy['Order_ID'].isin(['ĐN-2011-105648', 'HC-2011-140116'])]

,Order_ID,Order_Date,Order_Priority,Customer_ID,Customer_Name,Industry_name,Customer_Segment,Province,Region,Channel,...,Product_Category,Product_Sub-Category,Product_Name,Sales,Quantity,Unit_Price,Discount,Profit,Returned_Reason,Age_Group
147,ĐN-2011-105648,3/3/24,Low,EJ-14155,Eva Jacobs,Thiết bị gia dụng,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,25-34
164,HC-2011-140116,3/10/24,Low,KT-16480,Bùi Công Danh,Thiết bị gia dụng,Consumer,Hồ Chí Minh,Miền Đông Nam Bộ,Store,...,Hàng điện lạnh,Máy điều hòa,MÁY LẠNH GENERAL ASHG 015LHJI,636.408,3.0,212.136,0.2,-15.9102,NaN,35-44
165,HC-2011-140116,3/10/24,Medium,KT-16480,Bùi Công Danh,Thiết bị gia dụng,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,18-24

In [691]:
# check filtering condition before droping
df_copy[(df_copy['Order_ID'].isin(['ĐN-2011-105648', 'HC-2011-140116'])) & (df_copy['Customer_Segment'].isna())]

,Order_ID,Order_Date,Order_Priority,Customer_ID,Customer_Name,Industry_name,Customer_Segment,Province,Region,Channel,...,Product_Category,Product_Sub-Category,Product_Name,Sales,Quantity,Unit_Price,Discount,Profit,Returned_Reason,Age_Group
147,ĐN-2011-105648,3/3/24,Low,EJ-14155,Eva Jacobs,Thiết bị gia dụng,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,25-34
165,HC-2011-140116,3/10/24,Medium,KT-16480,Bùi Công Danh,Thiết bị gia dụng,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,18-24

In [692]:
# 1. Completeness: Checking and handling missing data
# 1.3 Check each column: Customer_Segment --> dropping data
df_copy = df_copy.drop(df_copy[(df_copy['Order_ID'].isin(['ĐN-2011-105648', 'HC-2011-140116'])) & (df_copy['Customer_Segment'].isna())].index)
## double check after dropping
df_copy[df_copy['Customer_Segment'].isna()]

Empty DataFrame
Columns: [Order_ID, Order_Date, Order_Priority, Customer_ID, Customer_Name, Industry_name, Customer_Segment, Province, Region, Channel, Product_ID, Product_Category, Product_Sub-Category, Product_Name, Sales, Quantity, Unit_Price, Discount, Profit, Returned_Reason, Age_Group]
Index: []

[0 rows x 21 columns]

In [693]:
# 1.1 Check Missing data
# 1.1.4 Check each column: Province
df_copy[df_copy['Province'].isna()]

Empty DataFrame
Columns: [Order_ID, Order_Date, Order_Priority, Customer_ID, Customer_Name, Industry_name, Customer_Segment, Province, Region, Channel, Product_ID, Product_Category, Product_Sub-Category, Product_Name, Sales, Quantity, Unit_Price, Discount, Profit, Returned_Reason, Age_Group]
Index: []

[0 rows x 21 columns]

In [694]:
# 1. Completeness: Checking and handling missing data
# 1.4 Check each column: Region
df_copy[df_copy['Region'].isna()]

,Order_ID,Order_Date,Order_Priority,Customer_ID,Customer_Name,Industry_name,Customer_Segment,Province,Region,Channel,...,Product_Category,Product_Sub-Category,Product_Name,Sales,Quantity,Unit_Price,Discount,Profit,Returned_Reason,Age_Group
497,HT-2011-127166,5/21/24,Low,KH-16360,Trần Đức,Thiết bị gia dụng,Consumer,Hà Tỉnh,NaN,Agent,...,Nội thất,Ghế,Ghế đa năng 3FC1006-P,107.772,2.0,53.886,0.3,-29.2524,NaN,18-24

In [695]:
# 1. Completeness: Checking and handling missing data
# 1.4 Check each column: Region -- Hà Tỉnh thuộc region Miền Trung. -> Replace Region NaN có Province = 'Hà Tỉnh' bằng "Miền Trung"
df_copy.loc[df_copy['Province'] == 'Hà Tỉnh', 'Region'] = 'Miền Trung'

In [696]:
df_copy[df_copy['Region'].isna()]

Empty DataFrame
Columns: [Order_ID, Order_Date, Order_Priority, Customer_ID, Customer_Name, Industry_name, Customer_Segment, Province, Region, Channel, Product_ID, Product_Category, Product_Sub-Category, Product_Name, Sales, Quantity, Unit_Price, Discount, Profit, Returned_Reason, Age_Group]
Index: []

[0 rows x 21 columns]

In [697]:
# 1. Completeness: Checking and handling missing data
# 1.5 Check each column: Channel, Product_ID, Product_Category,Product_Sub-Category, Product_Name
df_copy[df_copy['Channel'].isna()]
df_copy[df_copy['Product_ID'].isna()]
df_copy[df_copy['Product_Category'].isna()]
df_copy[df_copy['Product_Sub-Category'].isna()]
df_copy[df_copy['Product_Name'].isna()]

Empty DataFrame
Columns: [Order_ID, Order_Date, Order_Priority, Customer_ID, Customer_Name, Industry_name, Customer_Segment, Province, Region, Channel, Product_ID, Product_Category, Product_Sub-Category, Product_Name, Sales, Quantity, Unit_Price, Discount, Profit, Returned_Reason, Age_Group]
Index: []

[0 rows x 21 columns]

In [698]:
# 1. Completeness: Checking and handling missing data
# 1.6 Check each column: Sales, Quantity
# df_copy[df_copy['Sales'].isna()]
df_copy[df_copy['Quantity'].isna()]

Empty DataFrame
Columns: [Order_ID, Order_Date, Order_Priority, Customer_ID, Customer_Name, Industry_name, Customer_Segment, Province, Region, Channel, Product_ID, Product_Category, Product_Sub-Category, Product_Name, Sales, Quantity, Unit_Price, Discount, Profit, Returned_Reason, Age_Group]
Index: []

[0 rows x 21 columns]

In [699]:
# 1. Completeness: Checking and handling missing data
# 1.7 Check each column: Unit_Price
df_copy[df_copy['Unit_Price'].isna()]

,Order_ID,Order_Date,Order_Priority,Customer_ID,Customer_Name,Industry_name,Customer_Segment,Province,Region,Channel,...,Product_Category,Product_Sub-Category,Product_Name,Sales,Quantity,Unit_Price,Discount,Profit,Returned_Reason,Age_Group
3,NA-2011-112326,1/5/24,Low,PO-19195,Phillina Ober,Thiết bị gia dụng,Home Office,Nghệ An,Miền Đông Nam Bộ,Online,...,Hàng điện lạnh,Máy giặt,GBC Standard Plastic Binding Systems Combs,3.54,2.0,NaN,0.8,-5.4870,NaN,45
26,ĐT-2011-109232,1/14/24,High,ND-18370,Lê Nguyễn Thanh Giang,Thiết bị gia dụng,Consumer,Đồng Tháp,Miền Tây Nam Bộ,Agent,...,Nội thất,Ghế,Global Highback Leather Tilter in Burgundy,545.94,6.0,NaN,NaN,87.3504,NaN,45-54
57,ĐT-2011-167927,1/21/24,Medium,XP-21865,Tài Thị Hoa,Thiết bị gia dụng,Consumer,Đồng Tháp,Miền Tây Nam Bộ,Agent,...,Nội thất,Giường,Ultra Door Push Plate,14.73,3.0,NaN,0.0,4.8609,NaN,25-34
88,HN-2011-131905,2/7/24,Medium,ND-18460,Neil Ducich,Thiết bị gia dụng,Corporate,Hà Nội,Miền Bắc,Agent,...,Hàng điện lạnh,Máy điều hòa,MÁY LẠNH DAIKIN FTNE60MV1V,15.00,4.0,NaN,0.0,7.2000,NaN,>=55

In [700]:
# 1. Completeness: Checking and handling missing data
# 1.7 Check each column: Unit_Price = Sales/ Quantity
df_copy.loc[df_copy['Unit_Price'].isna(), 'Unit_Price'] = df_copy['Sales'] / df_copy['Quantity']

In [701]:
df_copy[df_copy['Unit_Price'].isna()]

Empty DataFrame
Columns: [Order_ID, Order_Date, Order_Priority, Customer_ID, Customer_Name, Industry_name, Customer_Segment, Province, Region, Channel, Product_ID, Product_Category, Product_Sub-Category, Product_Name, Sales, Quantity, Unit_Price, Discount, Profit, Returned_Reason, Age_Group]
Index: []

[0 rows x 21 columns]

In [702]:
# 1. Completeness: Checking and handling missing data
# 1.8 Check each column: Unit_Price
df_copy[df_copy['Discount'].isna()]

,Order_ID,Order_Date,Order_Priority,Customer_ID,Customer_Name,Industry_name,Customer_Segment,Province,Region,Channel,...,Product_Category,Product_Sub-Category,Product_Name,Sales,Quantity,Unit_Price,Discount,Profit,Returned_Reason,Age_Group
6,HC-2011-106054,1/7/24,Medium,JO-15145,Jack O'Briant,Thiết bị gia dụng,Corporate,Hồ Chí Minh,Miền Đông Nam Bộ,Online,...,Hàng điện lạnh,Máy giặt,"Dixon Prang Watercolor Pencils, 10-Color Set w...",12.78,3.0,4.26,NaN,5.2398,NaN,>=55
7,HN-2011-167199,1/7/24,High,ME-17320,Nguyễn Ca Hùng,Thiết bị gia dụng,Home Office,Hà Nội,Miền Bắc,Online,...,Nội thất,Ghế,Ghế làm việc 2MV2506-M1,2573.82,9.0,285.98,NaN,746.4078,NaN,35-44
8,HN-2011-167199,1/7/24,High,ME-17320,Nguyễn Ca Hùng,Thiết bị gia dụng,Home Office,Hà Nội,Miền Bắc,Online,...,Hàng điện lạnh,Máy giặt,Ibico Hi-Tech Manual Binding System,609.98,2.0,304.99,NaN,274.4910,NaN,18-24
9,HN-2011-167199,1/7/24,Medium,ME-17320,Nguyễn Ca Hùng,Thiết bị gia dụng,Home Office,Hà Nội,Miền Bắc,Online,...,Hàng điện lạnh,Máy giặt,Rogers Handheld Barrel Pencil Sharpener,5.48,2.0,2.74,NaN,1.4796,NaN,45-54
10,HN-2011-167199,1/7/24,High,ME-17320,Nguyễn Ca Hùng,Thiết bị điện tử,Home Office,Hà Nội,Miền Bắc,Online,...,Hàng điện tử,Phones,GE 30524EE4,-391.98,2.0,195.99,NaN,113.6742,NaN,35-44
11,HN-2011-167199,1/7/24,High,ME-17320,Nguyễn Ca Hùng,Thiết bị điện tử,Home Office,Hà Nội,Miền Bắc,Online,...,Hàng điện tử,Phones,Wireless Extenders zBoost YX545 SOHO Signal Bo...,755.96,4.0,188.99,NaN,204.1092,NaN,>=55
12,HN-2011-167199,1/7/24,High,ME-17320,Nguyễn Ca Hùng,Thiết bị gia dụng,Home Office,Hà Nội,Miền Bắc,Online,...,Hàng điện lạnh,Máy điều hòa,MÁY LẠNH CHA 51NVMV,31.12,4.0,7.78,NaN,0.3112,NaN,18-24
13,HN-2011-167199,1/7/24,Medium,ME-17320,Nguyễn Ca Hùng,Thiết bị gia dụng,Home Office,Hà Nội,Miền Bắc,Online,...,Hàng điện lạnh,Tủ lạnh,Miền Đông Nam Bộworth 25% Cotton Granite Tủ lạ...,6.54,1.0,6.54,NaN,3.0084,Damaged,45-54
18,HG-2011-149020,1/11/24,Medium,AJ-10780,Phạm Khanh,Thiết bị gia dụng,Corporate,Hà Giang,Miền Bắc,Store,...,Hàng điện lạnh,Máy điều hòa,MÁY LẠNH DAIKIN FTKC60NVMV-YTG,2.89,1.0,2.89,NaN,1.3583,NaN,>=55
19,HG-2011-149020,1/11/24,Medium,AJ-10780,Phạm Khanh,Thiết bị gia dụng,Corporate,Hà Giang,Miền Bắc,Store,...,Nội thất,Giường,"Howard Miller 11-1/2"" Diameter Ridgewood Wall ...",51.94,1.0,51.94,NaN,21.2954,NaN,25-34
20,VL-2011-130092,1/12/24,Medium,SV-20365,Seth Vernon,Thiết bị gia dụng,Consumer,Vĩnh Long,Miền Tây Nam Bộ,Store,...,Nội thất,Giường,"DAX Value U-Channel Document Frames, Easel Back",9.94,2.0,4.97,NaN,3.0814,NaN,18-24
21,HC-2011-162775,1/14/24,Medium,CS-12250,Trương Hồng Tâm,Thiết bị gia dụng,Corporate,Hồ Chí Minh,Miền Đông Nam Bộ,Online,...,Hàng điện lạnh,Tủ lạnh,MÁY LẠNH SHARP AH-AP12PMW,11.36,2.0,5.68,NaN,5.3392,NaN,>=55
22,HC-2011-162775,1/14/24,Medium,CS-12250,Trương Hồng Tâm,Thiết bị gia dụng,Corporate,Hồ Chí Minh,Miền Đông Nam Bộ,Online,...,Hàng điện lạnh,Tủ lạnh,Brown Kraft Recycled Tủ lạnh,50.94,3.0,16.98,NaN,25.4700,NaN,35-44
23,HC-2011-162775,1/14/24,High,CS-12250,Trương Hồng Tâm,Thiết bị điện tử,Corporate,Hồ Chí Minh,Miền Đông Nam Bộ,Online,...,Hàng điện tử,Accessories,Plantronics S12 Corded Telephone Headset System,646.74,6.0,107.79,NaN,258.6960,NaN,18-24
24,HC-2011-162775,1/14/24,Medium,CS-12250,Trương Hồng Tâm,Thiết bị gia dụng,Corporate,Hồ Chí Minh,Miền Đông Nam Bộ,Online,...,Hàng điện lạnh,Máy giặt,MÁY LẠNH SHARP AH-AP12PMW,5.64,3.0,1.88,NaN,2.7072,NaN,56
25,HC-2011-162775,1/14/24,Medium,CS-12250,Trương Hồng Tâm,Thiết bị gia dụng,Corporate,Hồ Chí Minh,Miền Đông Nam Bộ,Online,...,Hàng điện lạnh,Máy điều hòa,MÁY LẠNH LG G27PC,572.58,6.0,95.43,NaN,34.3548,NaN,45-54
26,ĐT-2011-109232,1/14/24,High,ND-18370,Lê Nguyễn Thanh Giang,Thiết bị gia dụng,Consumer,Đồng Tháp,Miền Tây Nam Bộ,Agent,...,Nội thất,Ghế,Global Highback Leather Tilter in Burgundy,545.94,6.0,90.99,NaN,87.3504,NaN,45-54
27,ĐN-2011-157147,1/14/24,High,BD-11605,Nguyễn Văn Tài Em,Thiết bị gia dụng,Consumer,Đà Nẵng,Miền Trung,Agent,...,Hàng điện lạnh,Máy điều hòa,MÁY LẠNH GENERAL ASHG 015LHJI,1325.85,5.0,265.17,NaN,238.6530,NaN,18-24
29,ĐN-2011-157147,1/14/24,Medium,BD-11605,Nguyễn Văn Tài Em,Thiết bị gia dụng,Consumer,Đà Nẵng,Miền Trung,Agent,...,Hàng điện lạnh,Máy giặt,4009 Highlighters by Sanford,19.90,5.0,3.98,NaN,6.5670,NaN,45-54
33,ĐN-2011-103366,1/16/24,High,EH-13990,Erica Hackney,Thiết bị điện tử,Consumer,Đà Nẵng,Miền Trung,Agent,...,Hàng điện tử,Accessories,Logitech 910-002974 M325 Wireless Mouse for We...,149.95,5.0,29.99,NaN,65.9780,NaN,45-54

In [703]:
# 1. Completeness: Checking and handling missing data
# 1.8 Check each column: Discount. --> Filling = 0
df_copy['Discount'].fillna(0, inplace=True)
df_copy[df_copy['Discount'].isna()]

<ipython-input-703-53f0bbcf2eda>:3: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df_copy['Discount'].fillna(0, inplace=True)

Empty DataFrame
Columns: [Order_ID, Order_Date, Order_Priority, Customer_ID, Customer_Name, Industry_name, Customer_Segment, Province, Region, Channel, Product_ID, Product_Category, Product_Sub-Category, Product_Name, Sales, Quantity, Unit_Price, Discount, Profit, Returned_Reason, Age_Group]
Index: []

[0 rows x 21 columns]

In [704]:
# 1. Completeness: Checking and handling missing data
# 1.9 Check each column: Age_Group
df_copy[df_copy['Age_Group'].isna()]

Empty DataFrame
Columns: [Order_ID, Order_Date, Order_Priority, Customer_ID, Customer_Name, Industry_name, Customer_Segment, Province, Region, Channel, Product_ID, Product_Category, Product_Sub-Category, Product_Name, Sales, Quantity, Unit_Price, Discount, Profit, Returned_Reason, Age_Group]
Index: []

[0 rows x 21 columns]

In [705]:
# 1. Completeness: Checking and handling missing data
# 1.10 Check each column: Returned_Reason
df_copy[df_copy['Returned_Reason'].isna()]

,Order_ID,Order_Date,Order_Priority,Customer_ID,Customer_Name,Industry_name,Customer_Segment,Province,Region,Channel,...,Product_Category,Product_Sub-Category,Product_Name,Sales,Quantity,Unit_Price,Discount,Profit,Returned_Reason,Age_Group
3,NA-2011-112326,1/5/24,Low,PO-19195,Phillina Ober,Thiết bị gia dụng,Home Office,Nghệ An,Miền Đông Nam Bộ,Online,...,Hàng điện lạnh,Máy giặt,GBC Standard Plastic Binding Systems Combs,3.540,2.0,1.770,0.8,-5.4870,NaN,45
4,TN-2011-141817,1/6/24,Medium,MB-18085,Trần Nhiễm,Thiết bị gia dụng,Consumer,Tây Ninh,Miền Đông Nam Bộ,Store,...,Hàng điện lạnh,Máy giặt,Avery Hi-Liter EverBold Pen Style Fluorescent ...,19.536,3.0,6.512,0.2,4.8840,NaN,25-34
5,ĐN-2011-130813,1/7/24,Medium,LS-17230,Lycoris Saunders,Thiết bị gia dụng,Consumer,Đồng Nai,Miền Đông Nam Bộ,Store,...,Hàng điện lạnh,Tủ lạnh,Xerox 225,19.440,3.0,6.480,0.0,9.3312,NaN,35-44
6,HC-2011-106054,1/7/24,Medium,JO-15145,Jack O'Briant,Thiết bị gia dụng,Corporate,Hồ Chí Minh,Miền Đông Nam Bộ,Online,...,Hàng điện lạnh,Máy giặt,"Dixon Prang Watercolor Pencils, 10-Color Set w...",12.780,3.0,4.260,0.0,5.2398,NaN,>=55
7,HN-2011-167199,1/7/24,High,ME-17320,Nguyễn Ca Hùng,Thiết bị gia dụng,Home Office,Hà Nội,Miền Bắc,Online,...,Nội thất,Ghế,Ghế làm việc 2MV2506-M1,2573.820,9.0,285.980,0.0,746.4078,NaN,35-44
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
498,HT-2011-127166,5/21/24,Medium,KH-16360,Trần Đức,Thiết bị gia dụng,Consumer,Hà Tỉnh,Miền Trung,Agent,...,Hàng điện lạnh,Tủ lạnh,"Adams Telephone Message Books, 5 1/4” x 11”",4.832,1.0,4.832,0.2,1.6308,NaN,>=55
499,HT-2011-127166,5/21/24,Low,KH-16360,Trần Đức,Thiết bị gia dụng,Consumer,Hà Tỉnh,Miền Trung,Agent,...,Hàng điện lạnh,Máy giặt,Ibico Plastic Spiral Binding Combs,18.240,3.0,6.080,0.8,-31.0080,NaN,>=55
500,HT-2011-127166,5/21/24,Low,KH-16360,Trần Đức,Thiết bị gia dụng,Consumer,Hà Tỉnh,Miền Trung,Agent,...,Hàng điện lạnh,Máy giặt,Ibico Plastic Spiral Binding Combs,18.240,3.0,6.080,0.8,-31.0080,NaN,>=55
501,HC-2011-130673,5/20/24,Low,MC-17590,Nguyễn Thị Thu Hường,Thiết bị gia dụng,Corporate,Hồ Chí Minh,Miền Đông Nam Bộ,Agent,...,Hàng điện lạnh,Máy điều hòa,Rogers Profile Extra Capacity Máy điều hòa Tub,66.960,5.0,13.392,0.2,-13.3920,NaN,25-34
502,HC-2011-113768,5/13/24,Medium,AH-10030,Trương Thanh Vân,Thiết bị gia dụng,Corporate,Hồ Chí Minh,Miền Đông Nam Bộ,Agent,...,Nội thất,Ghế,"Iceberg Nesting Folding Chair, 19w x 6d x 43h",279.456,6.0,46.576,0.2,20.9592,NaN,18-24

## 2. Accuracy

Remarks

- Check distribution of numerical columns: df.describe()
- Check and review each column
- Replace by valid value / a calculation

In [706]:
df_copy

,Order_ID,Order_Date,Order_Priority,Customer_ID,Customer_Name,Industry_name,Customer_Segment,Province,Region,Channel,...,Product_Category,Product_Sub-Category,Product_Name,Sales,Quantity,Unit_Price,Discount,Profit,Returned_Reason,Age_Group
0,HC-2011-103800,1/4/24,Medium,DP-13000,Darren Tran,Thiết bị gia dụng,Consumer,Hồ Chí Minh,Miền Đông Nam Bộ,Store,...,Hàng điện lạnh,Tủ lạnh,"Message Book, Wirebound, Four 5 1/2"" X 4"" Form...",16.448,2.0,8.224,0.2,5.5512,No reason,>=55
1,NA-2011-112326,2024.01.05,Medium,PO-19195,Phillina Ober,Thiết bị gia dụng,Home Office,Nghệ An,Miền Trung,Online,...,Hàng điện lạnh,Máy điều hòa,MÁY LẠNH DAIKIN FTKC60NVMV-BBB,11.784,3.0,3.928,0.2,4.2717,"""""",35-44
2,NA-2011-112326,1/5/24,Low,PO-19195,Phillina Ober,Thiết bị gia dụng,Home Office,Nghệ An,Miền Trung,Online,...,Hàng điện lạnh,Máy điều hòa,MÁY LẠNH LG V13BPB,272.736,3.0,90.912,0.2,-64.7748,"""""",>=55
3,NA-2011-112326,1/5/24,Low,PO-19195,Phillina Ober,Thiết bị gia dụng,Home Office,Nghệ An,Miền Đông Nam Bộ,Online,...,Hàng điện lạnh,Máy giặt,GBC Standard Plastic Binding Systems Combs,3.540,2.0,1.770,0.8,-5.4870,NaN,45
4,TN-2011-141817,1/6/24,Medium,MB-18085,Trần Nhiễm,Thiết bị gia dụng,Consumer,Tây Ninh,Miền Đông Nam Bộ,Store,...,Hàng điện lạnh,Máy giặt,Avery Hi-Liter EverBold Pen Style Fluorescent ...,19.536,3.0,6.512,0.2,4.8840,NaN,25-34
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
498,HT-2011-127166,5/21/24,Medium,KH-16360,Trần Đức,Thiết bị gia dụng,Consumer,Hà Tỉnh,Miền Trung,Agent,...,Hàng điện lạnh,Tủ lạnh,"Adams Telephone Message Books, 5 1/4” x 11”",4.832,1.0,4.832,0.2,1.6308,NaN,>=55
499,HT-2011-127166,5/21/24,Low,KH-16360,Trần Đức,Thiết bị gia dụng,Consumer,Hà Tỉnh,Miền Trung,Agent,...,Hàng điện lạnh,Máy giặt,Ibico Plastic Spiral Binding Combs,18.240,3.0,6.080,0.8,-31.0080,NaN,>=55
500,HT-2011-127166,5/21/24,Low,KH-16360,Trần Đức,Thiết bị gia dụng,Consumer,Hà Tỉnh,Miền Trung,Agent,...,Hàng điện lạnh,Máy giặt,Ibico Plastic Spiral Binding Combs,18.240,3.0,6.080,0.8,-31.0080,NaN,>=55
501,HC-2011-130673,5/20/24,Low,MC-17590,Nguyễn Thị Thu Hường,Thiết bị gia dụng,Corporate,Hồ Chí Minh,Miền Đông Nam Bộ,Agent,...,Hàng điện lạnh,Máy điều hòa,Rogers Profile Extra Capacity Máy điều hòa Tub,66.960,5.0,13.392,0.2,-13.3920,NaN,25-34
502,HC-2011-113768,5/13/24,Medium,AH-10030,Trương Thanh Vân,Thiết bị gia dụng,Corporate,Hồ Chí Minh,Miền Đông Nam Bộ,Agent,...,Nội thất,Ghế,"Iceberg Nesting Folding Chair, 19w x 6d x 43h",279.456,6.0,46.576,0.2,20.9592,NaN,18-24

In [707]:
df_copy.info()

<class 'pandas.core.frame.DataFrame'>
Index: 498 entries, 0 to 502
Data columns (total 21 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   Order_ID              498 non-null    object
 1   Order_Date            498 non-null    object
 2   Order_Priority        498 non-null    object
 3   Customer_ID           498 non-null    object
 4   Customer_Name         498 non-null    object
 5   Industry_name         498 non-null    object
 6   Customer_Segment      498 non-null    object
 7   Province              498 non-null    object
 8   Region                498 non-null    object
 9   Channel               498 non-null    object
 10  Product_ID            498 non-null    object
 11  Product_Category      498 non-null    object
 12  Product_Sub-Category  498 non-null    object
 13  Product_Name          498 non-null    object
 14  Sales                 498 non-null    float64
 15  Quantity              498 non-null    float64
 16  Unit_Price            498 non-null    float64
 17  Discount              498 non-null    float64
 18  Profit                498 non-null    float64
 19  Returned_Reason       10 non-null     object
 20  Age_Group             498 non-null    object
dtypes: float64(5), object(16)
memory usage: 101.8+ KB

In [708]:
df_copy.describe()

              Sales    Quantity   Unit_Price    Discount       Profit
count    498.000000  498.000000   498.000000  498.000000   498.000000
mean     234.675910    3.757028    58.096884    0.144076    18.072685
std     1084.483098    2.286167   187.192857    0.198840   137.473359
min     -391.980000   -4.000000     0.360000   -0.100000 -1811.078400
25%       16.560000    2.000000     5.184000    0.000000     2.255750
50%       46.832000    3.000000    13.371000    0.000000     7.236500
75%      166.380000    5.000000    55.480000    0.200000    23.798100
max    22638.480000   14.000000  3773.080000    0.800000  1276.487100

**Remarks: **

Sales, Quantity, Discount columns contain negative value --> **NOT MAKE SENSE**
---> Solution:


*   Double check carefully for each column
*   Replace by valid value

In [709]:
# 2. Accuracy
# 2.1 Review data in Sales column
df_copy[df_copy['Sales'] < 0]

,Order_ID,Order_Date,Order_Priority,Customer_ID,Customer_Name,Industry_name,Customer_Segment,Province,Region,Channel,...,Product_Category,Product_Sub-Category,Product_Name,Sales,Quantity,Unit_Price,Discount,Profit,Returned_Reason,Age_Group
10,HN-2011-167199,1/7/24,High,ME-17320,Nguyễn Ca Hùng,Thiết bị điện tử,Home Office,Hà Nội,Miền Bắc,Online,...,Hàng điện tử,Phones,GE 30524EE4,-391.98,2.0,195.99,0.0,113.6742,NaN,35-44
94,HN-2011-125759,2/9/24,Medium,NM-18445,Nguyễn Cát Phương,Thiết bị gia dụng,Home Office,Hà Nội,Miền Bắc,Store,...,Nội thất,Giường,"Master Caster Door Stop, Large Brown",-14.56,2.0,7.28,0.0,5.5328,NaN,>=55

In [710]:
# 2. Accuracy
# 2.1 Review data in Sales column: replace by abs value
df_copy.loc[df_copy['Sales'] < 0, 'Sales'] = df_copy['Sales'].abs()
# 2.1 Review data in Sales column: replace by a calculation: Quantity * Unit_Price
# df_copy.loc[df_copy['Sales'] < 0, 'Sales'] = df_copy['Quantity'] * df_copy['Unit_Price']

In [711]:
# 2. Accuracy
# 2.2 Review data in Quantity column: replace by abs value
df_copy[df_copy['Quantity'] < 0]
df_copy.loc[df_copy['Quantity'] < 0, 'Quantity'] = df_copy['Quantity'].abs()

In [712]:
# 2. Accuracy
# 2.3 Review data in Discount column: replace by abs value
df_copy[df_copy['Discount'] < 0]
df_copy.loc[df_copy['Discount'] < 0, 'Discount'] = df_copy['Discount'].abs()

## 3. Validity & Consistency

**Step by step**
- List all categorical columns with 20 or fewer unique categories.
- Inspect the data in each column to identify errors.
- Replace invalid values with correct ones:
   + Standardize misspelled data.
   + Fill missing values (NaN) with the most common value (mode).
- Double check carefully after handling

In [713]:
df_copy

,Order_ID,Order_Date,Order_Priority,Customer_ID,Customer_Name,Industry_name,Customer_Segment,Province,Region,Channel,...,Product_Category,Product_Sub-Category,Product_Name,Sales,Quantity,Unit_Price,Discount,Profit,Returned_Reason,Age_Group
0,HC-2011-103800,1/4/24,Medium,DP-13000,Darren Tran,Thiết bị gia dụng,Consumer,Hồ Chí Minh,Miền Đông Nam Bộ,Store,...,Hàng điện lạnh,Tủ lạnh,"Message Book, Wirebound, Four 5 1/2"" X 4"" Form...",16.448,2.0,8.224,0.2,5.5512,No reason,>=55
1,NA-2011-112326,2024.01.05,Medium,PO-19195,Phillina Ober,Thiết bị gia dụng,Home Office,Nghệ An,Miền Trung,Online,...,Hàng điện lạnh,Máy điều hòa,MÁY LẠNH DAIKIN FTKC60NVMV-BBB,11.784,3.0,3.928,0.2,4.2717,"""""",35-44
2,NA-2011-112326,1/5/24,Low,PO-19195,Phillina Ober,Thiết bị gia dụng,Home Office,Nghệ An,Miền Trung,Online,...,Hàng điện lạnh,Máy điều hòa,MÁY LẠNH LG V13BPB,272.736,3.0,90.912,0.2,-64.7748,"""""",>=55
3,NA-2011-112326,1/5/24,Low,PO-19195,Phillina Ober,Thiết bị gia dụng,Home Office,Nghệ An,Miền Đông Nam Bộ,Online,...,Hàng điện lạnh,Máy giặt,GBC Standard Plastic Binding Systems Combs,3.540,2.0,1.770,0.8,-5.4870,NaN,45
4,TN-2011-141817,1/6/24,Medium,MB-18085,Trần Nhiễm,Thiết bị gia dụng,Consumer,Tây Ninh,Miền Đông Nam Bộ,Store,...,Hàng điện lạnh,Máy giặt,Avery Hi-Liter EverBold Pen Style Fluorescent ...,19.536,3.0,6.512,0.2,4.8840,NaN,25-34
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
498,HT-2011-127166,5/21/24,Medium,KH-16360,Trần Đức,Thiết bị gia dụng,Consumer,Hà Tỉnh,Miền Trung,Agent,...,Hàng điện lạnh,Tủ lạnh,"Adams Telephone Message Books, 5 1/4” x 11”",4.832,1.0,4.832,0.2,1.6308,NaN,>=55
499,HT-2011-127166,5/21/24,Low,KH-16360,Trần Đức,Thiết bị gia dụng,Consumer,Hà Tỉnh,Miền Trung,Agent,...,Hàng điện lạnh,Máy giặt,Ibico Plastic Spiral Binding Combs,18.240,3.0,6.080,0.8,-31.0080,NaN,>=55
500,HT-2011-127166,5/21/24,Low,KH-16360,Trần Đức,Thiết bị gia dụng,Consumer,Hà Tỉnh,Miền Trung,Agent,...,Hàng điện lạnh,Máy giặt,Ibico Plastic Spiral Binding Combs,18.240,3.0,6.080,0.8,-31.0080,NaN,>=55
501,HC-2011-130673,5/20/24,Low,MC-17590,Nguyễn Thị Thu Hường,Thiết bị gia dụng,Corporate,Hồ Chí Minh,Miền Đông Nam Bộ,Agent,...,Hàng điện lạnh,Máy điều hòa,Rogers Profile Extra Capacity Máy điều hòa Tub,66.960,5.0,13.392,0.2,-13.3920,NaN,25-34
502,HC-2011-113768,5/13/24,Medium,AH-10030,Trương Thanh Vân,Thiết bị gia dụng,Corporate,Hồ Chí Minh,Miền Đông Nam Bộ,Agent,...,Nội thất,Ghế,"Iceberg Nesting Folding Chair, 19w x 6d x 43h",279.456,6.0,46.576,0.2,20.9592,NaN,18-24

In [714]:
# 3. Validity
# 3.1 Identify categorical columns with 20 or fewer unique values.
categorical_cols = [col for col in df_copy.select_dtypes(include=['object']).columns if df_copy[col].nunique() <= 20]
print("Identify categorical columns with 20 or fewer unique valuesc:", categorical_cols)

Identify categorical columns with 20 or fewer unique valuesc: ['Order_Priority', 'Industry_name', 'Customer_Segment', 'Region', 'Channel', 'Product_Category', 'Product_Sub-Category', 'Returned_Reason', 'Age_Group']

In [715]:
# 3. Validity
# 3.2 Inspect the data in each column to identify errors.
for col in categorical_cols:
    print(f"🔹 Column: {col}")
    print(df_copy[col].value_counts(dropna=False))  # Hiển thị số lần xuất hiện của từng giá trị (kể cả NaN)
    print("-" * 50)

🔹 Column: Order_Priority
Order_Priority
Medium    329
Low        89
High       80
Name: count, dtype: int64
--------------------------------------------------
🔹 Column: Industry_name
Industry_name
Thiết bị gia dụng    419
Thiết bị điện tử      79
Name: count, dtype: int64
--------------------------------------------------
🔹 Column: Customer_Segment
Customer_Segment
Consumer       247
Corporate      160
Home Office     91
Name: count, dtype: int64
--------------------------------------------------
🔹 Column: Region
Region
Miền Đông Nam Bộ    200
Miền Trung          152
Miền Bắc             96
Miền Tây Nam Bộ      46
""                    2
'                     1
Hà Nội                1
Name: count, dtype: int64
--------------------------------------------------
🔹 Column: Channel
Channel
Agent             222
Store             160
Online             95
agent              14
online channel      7
Name: count, dtype: int64
--------------------------------------------------
🔹 Column: Product_Category
Product_Category
Hàng điện lạnh    294
Nội thất          104
Hàng điện tử       76
Điện lạnh          21
Điện tử             3
Name: count, dtype: int64
--------------------------------------------------
🔹 Column: Product_Sub-Category
Product_Sub-Category
Máy giặt        149
Tủ lạnh          85
Máy điều hòa     81
Giường           44
Phones           36
Accessories      36
Ghế              32
Bàn              18
Kệ sách          10
Machines          5
Copiers           2
Name: count, dtype: int64
--------------------------------------------------
🔹 Column: Returned_Reason
Returned_Reason
NaN           488
""              4
Wrong item      3
Damaged         2
No reason       1
Name: count, dtype: int64
--------------------------------------------------
🔹 Column: Age_Group
Age_Group
>=55     107
35-44    107
25-34    100
45-54     98
18-24     83
45         1
56         1
22         1
Name: count, dtype: int64
--------------------------------------------------

Remarks:
Need to handle columns: Product_Category, Channel, Region, Returned_Reason

In [716]:
# 3. Validity
# 3.3 Standardize misspelled data.
# Region
df_copy['Region'] = df_copy['Region'].replace({
    'Hà Nội': 'Miền Bắc',
    'Mien Bac': 'Miền Bắc',
    'Mien Nam': 'Miền Nam'
})

In [717]:
# 3. Validity
# 3.3 Standardize misspelled data.
# Region
df_copy[df_copy['Region']=='""']
df_copy.loc[df_copy['Province'] == 'Phú Thọ', 'Region'] = 'Miền Bắc'
df_copy.loc[df_copy['Province'] == 'Khánh Hòa', 'Region'] = 'Miền Trung'

In [718]:
# 3. Validity
# 3.3 Standardize misspelled data.
# Region
df_copy[df_copy['Region']=="'"]
df_copy.loc[df_copy['Province'] == 'Vĩnh Phúc', 'Region'] = 'Miền Bắc'

In [719]:
# 3. Validity
# 3.3 Standardize misspelled data.
# Double check
for col in categorical_cols:
    print(f"✅ Column {col} after handling:")
    print(df_copy[col].value_counts())
    print("-" * 50)

✅ Column Order_Priority after handling:
Order_Priority
Medium    329
Low        89
High       80
Name: count, dtype: int64
--------------------------------------------------
✅ Column Industry_name after handling:
Industry_name
Thiết bị gia dụng    419
Thiết bị điện tử      79
Name: count, dtype: int64
--------------------------------------------------
✅ Column Customer_Segment after handling:
Customer_Segment
Consumer       247
Corporate      160
Home Office     91
Name: count, dtype: int64
--------------------------------------------------
✅ Column Region after handling:
Region
Miền Đông Nam Bộ    200
Miền Trung          152
Miền Bắc            100
Miền Tây Nam Bộ      46
Name: count, dtype: int64
--------------------------------------------------
✅ Column Channel after handling:
Channel
Agent             222
Store             160
Online             95
agent              14
online channel      7
Name: count, dtype: int64
--------------------------------------------------
✅ Column Product_Category after handling:
Product_Category
Hàng điện lạnh    294
Nội thất          104
Hàng điện tử       76
Điện lạnh          21
Điện tử             3
Name: count, dtype: int64
--------------------------------------------------
✅ Column Product_Sub-Category after handling:
Product_Sub-Category
Máy giặt        149
Tủ lạnh          85
Máy điều hòa     81
Giường           44
Phones           36
Accessories      36
Ghế              32
Bàn              18
Kệ sách          10
Machines          5
Copiers           2
Name: count, dtype: int64
--------------------------------------------------
✅ Column Returned_Reason after handling:
Returned_Reason
""            4
Wrong item    3
Damaged       2
No reason     1
Name: count, dtype: int64
--------------------------------------------------
✅ Column Age_Group after handling:
Age_Group
>=55     107
35-44    107
25-34    100
45-54     98
18-24     83
45         1
56         1
22         1
Name: count, dtype: int64
--------------------------------------------------

In [720]:
# 3. Validity
# 3.4 Standardize misspelled data.
# Channel and Product_Category
df_copy['Product_Category'] = df_copy['Product_Category'].replace({
    'Điện lạnh': 'Hàng điện lạnh',
    'Điện tử': 'Hàng điện tử'
})

df_copy['Channel'] = df_copy['Channel'].replace({
    'agent': 'Agent',
    'online channel': 'Online'
})
# Double check
for col in categorical_cols:
    print(f"✅ Column {col} after handling:")
    print(df_copy[col].value_counts())
    print("-" * 50)

✅ Column Order_Priority after handling:
Order_Priority
Medium    329
Low        89
High       80
Name: count, dtype: int64
--------------------------------------------------
✅ Column Industry_name after handling:
Industry_name
Thiết bị gia dụng    419
Thiết bị điện tử      79
Name: count, dtype: int64
--------------------------------------------------
✅ Column Customer_Segment after handling:
Customer_Segment
Consumer       247
Corporate      160
Home Office     91
Name: count, dtype: int64
--------------------------------------------------
✅ Column Region after handling:
Region
Miền Đông Nam Bộ    200
Miền Trung          152
Miền Bắc            100
Miền Tây Nam Bộ      46
Name: count, dtype: int64
--------------------------------------------------
✅ Column Channel after handling:
Channel
Agent     236
Store     160
Online    102
Name: count, dtype: int64
--------------------------------------------------
✅ Column Product_Category after handling:
Product_Category
Hàng điện lạnh    315
Nội thất          104
Hàng điện tử       79
Name: count, dtype: int64
--------------------------------------------------
✅ Column Product_Sub-Category after handling:
Product_Sub-Category
Máy giặt        149
Tủ lạnh          85
Máy điều hòa     81
Giường           44
Phones           36
Accessories      36
Ghế              32
Bàn              18
Kệ sách          10
Machines          5
Copiers           2
Name: count, dtype: int64
--------------------------------------------------
✅ Column Returned_Reason after handling:
Returned_Reason
""            4
Wrong item    3
Damaged       2
No reason     1
Name: count, dtype: int64
--------------------------------------------------
✅ Column Age_Group after handling:
Age_Group
>=55     107
35-44    107
25-34    100
45-54     98
18-24     83
45         1
56         1
22         1
Name: count, dtype: int64
--------------------------------------------------

In [721]:
# 3. Validity
# 3.5 Standardize misspelled data.
# Returned_Reason
df_copy[df_copy['Returned_Reason'] == '""']
import numpy as np
df_copy.replace('""', np.nan, inplace=True)

# Double check
for col in categorical_cols:
    print(f"✅ Column {col} after handling:")
    print(df_copy[col].value_counts())
    print("-" * 50)

✅ Column Order_Priority after handling:
Order_Priority
Medium    329
Low        89
High       80
Name: count, dtype: int64
--------------------------------------------------
✅ Column Industry_name after handling:
Industry_name
Thiết bị gia dụng    419
Thiết bị điện tử      79
Name: count, dtype: int64
--------------------------------------------------
✅ Column Customer_Segment after handling:
Customer_Segment
Consumer       247
Corporate      160
Home Office     91
Name: count, dtype: int64
--------------------------------------------------
✅ Column Region after handling:
Region
Miền Đông Nam Bộ    200
Miền Trung          152
Miền Bắc            100
Miền Tây Nam Bộ      46
Name: count, dtype: int64
--------------------------------------------------
✅ Column Channel after handling:
Channel
Agent     236
Store     160
Online    102
Name: count, dtype: int64
--------------------------------------------------
✅ Column Product_Category after handling:
Product_Category
Hàng điện lạnh    315
Nội thất          104
Hàng điện tử       79
Name: count, dtype: int64
--------------------------------------------------
✅ Column Product_Sub-Category after handling:
Product_Sub-Category
Máy giặt        149
Tủ lạnh          85
Máy điều hòa     81
Giường           44
Phones           36
Accessories      36
Ghế              32
Bàn              18
Kệ sách          10
Machines          5
Copiers           2
Name: count, dtype: int64
--------------------------------------------------
✅ Column Returned_Reason after handling:
Returned_Reason
Wrong item    3
Damaged       2
No reason     1
Name: count, dtype: int64
--------------------------------------------------
✅ Column Age_Group after handling:
Age_Group
>=55     107
35-44    107
25-34    100
45-54     98
18-24     83
45         1
56         1
22         1
Name: count, dtype: int64
--------------------------------------------------

In [722]:
df_numeric = df_copy[pd.to_numeric(df_copy['Age_Group'], errors='coerce').notna()]
df_numeric

,Order_ID,Order_Date,Order_Priority,Customer_ID,Customer_Name,Industry_name,Customer_Segment,Province,Region,Channel,...,Product_Category,Product_Sub-Category,Product_Name,Sales,Quantity,Unit_Price,Discount,Profit,Returned_Reason,Age_Group
3,NA-2011-112326,1/5/24,Low,PO-19195,Phillina Ober,Thiết bị gia dụng,Home Office,Nghệ An,Miền Đông Nam Bộ,Online,...,Hàng điện lạnh,Máy giặt,GBC Standard Plastic Binding Systems Combs,3.540,2.0,1.770,0.8,-5.4870,NaN,45
24,HC-2011-162775,1/14/24,Medium,CS-12250,Trương Hồng Tâm,Thiết bị gia dụng,Corporate,Hồ Chí Minh,Miền Đông Nam Bộ,Online,...,Hàng điện lạnh,Máy giặt,MÁY LẠNH SHARP AH-AP12PMW,5.640,3.0,1.880,0.0,2.7072,NaN,56
105,ĐN-2011-107706,2/15/24,Medium,ST-20530,Nguyễn Thị Hằng Ngân,Thiết bị gia dụng,Consumer,Đồng Nai,Miền Đông Nam Bộ,Agent,...,Hàng điện lạnh,Tủ lạnh,"Memo Book, 100 Message Capacity, 5 3/8” x 11”",16.176,3.0,5.392,0.2,6.0660,NaN,22

In [723]:
df_numeric = df_copy[df_copy['Age_Group'].astype(str).str.isnumeric()]
df_numeric

,Order_ID,Order_Date,Order_Priority,Customer_ID,Customer_Name,Industry_name,Customer_Segment,Province,Region,Channel,...,Product_Category,Product_Sub-Category,Product_Name,Sales,Quantity,Unit_Price,Discount,Profit,Returned_Reason,Age_Group
3,NA-2011-112326,1/5/24,Low,PO-19195,Phillina Ober,Thiết bị gia dụng,Home Office,Nghệ An,Miền Đông Nam Bộ,Online,...,Hàng điện lạnh,Máy giặt,GBC Standard Plastic Binding Systems Combs,3.540,2.0,1.770,0.8,-5.4870,NaN,45
24,HC-2011-162775,1/14/24,Medium,CS-12250,Trương Hồng Tâm,Thiết bị gia dụng,Corporate,Hồ Chí Minh,Miền Đông Nam Bộ,Online,...,Hàng điện lạnh,Máy giặt,MÁY LẠNH SHARP AH-AP12PMW,5.640,3.0,1.880,0.0,2.7072,NaN,56
105,ĐN-2011-107706,2/15/24,Medium,ST-20530,Nguyễn Thị Hằng Ngân,Thiết bị gia dụng,Consumer,Đồng Nai,Miền Đông Nam Bộ,Agent,...,Hàng điện lạnh,Tủ lạnh,"Memo Book, 100 Message Capacity, 5 3/8” x 11”",16.176,3.0,5.392,0.2,6.0660,NaN,22

In [724]:
# # 3. Validity
# # 3.5 Standardize misspelled data.
# # Age_Group
# df_copy.loc[df_copy['Age_Group'] == '45', 'Age_Group'] = '45-54'
# df_copy.loc[df_copy['Age_Group'] == '56', 'Age_Group'] = '>=55'
# df_copy.loc[df_copy['Age_Group'] == '22', 'Age_Group'] = '18-24'

In [725]:
# Tạo danh sách giá trị hợp lệ
valid_age_groups = ['18-24', '25-34', '35-44', '45-54', '>=55']

# Chuyển cột Age_Group thành dạng chuỗi (để tránh lỗi so sánh dtype)
df_copy['Age_Group'] = df_copy['Age_Group'].astype(str)

# Chuyển các giá trị có thể thành số, giữ nguyên nếu không chuyển được
df_copy['Age_Group_Numeric'] = pd.to_numeric(df_copy['Age_Group'], errors='coerce')

# Điều kiện nhóm tuổi
conditions = [
    (df_copy['Age_Group_Numeric'] >= 18) & (df_copy['Age_Group_Numeric'] <= 24),
    (df_copy['Age_Group_Numeric'] >= 25) & (df_copy['Age_Group_Numeric'] <= 34),
    (df_copy['Age_Group_Numeric'] >= 35) & (df_copy['Age_Group_Numeric'] <= 44),
    (df_copy['Age_Group_Numeric'] >= 45) & (df_copy['Age_Group_Numeric'] <= 54),
    (df_copy['Age_Group_Numeric'] >= 55)
]

# Nhóm tuổi tương ứng
age_labels = ['18-24', '25-34', '35-44', '45-54', '>=55']

# Chỉ thay thế nếu giá trị không thuộc danh sách hợp lệ
df_copy['Age_Group'] = np.where(
    df_copy['Age_Group'].isin(valid_age_groups),  # Nếu đã hợp lệ
    df_copy['Age_Group'],  # Giữ nguyên
    np.select(conditions, age_labels, default="Unknown")  # Thay thế nếu sai
)

# Xóa cột trung gian
df_copy.drop(columns=['Age_Group_Numeric'], inplace=True)

# Kiểm tra kết quả
print(df_copy['Age_Group'].value_counts())

Age_Group
>=55     108
35-44    107
25-34    100
45-54     99
18-24     84
Name: count, dtype: int64

In [726]:
# Double check
for col in categorical_cols:
    print(f"✅ Column {col} after handling:")
    print(df_copy[col].value_counts())
    print("-" * 50)

✅ Column Order_Priority after handling:
Order_Priority
Medium    329
Low        89
High       80
Name: count, dtype: int64
--------------------------------------------------
✅ Column Industry_name after handling:
Industry_name
Thiết bị gia dụng    419
Thiết bị điện tử      79
Name: count, dtype: int64
--------------------------------------------------
✅ Column Customer_Segment after handling:
Customer_Segment
Consumer       247
Corporate      160
Home Office     91
Name: count, dtype: int64
--------------------------------------------------
✅ Column Region after handling:
Region
Miền Đông Nam Bộ    200
Miền Trung          152
Miền Bắc            100
Miền Tây Nam Bộ      46
Name: count, dtype: int64
--------------------------------------------------
✅ Column Channel after handling:
Channel
Agent     236
Store     160
Online    102
Name: count, dtype: int64
--------------------------------------------------
✅ Column Product_Category after handling:
Product_Category
Hàng điện lạnh    315
Nội thất          104
Hàng điện tử       79
Name: count, dtype: int64
--------------------------------------------------
✅ Column Product_Sub-Category after handling:
Product_Sub-Category
Máy giặt        149
Tủ lạnh          85
Máy điều hòa     81
Giường           44
Phones           36
Accessories      36
Ghế              32
Bàn              18
Kệ sách          10
Machines          5
Copiers           2
Name: count, dtype: int64
--------------------------------------------------
✅ Column Returned_Reason after handling:
Returned_Reason
Wrong item    3
Damaged       2
No reason     1
Name: count, dtype: int64
--------------------------------------------------
✅ Column Age_Group after handling:
Age_Group
>=55     108
35-44    107
25-34    100
45-54     99
18-24     84
Name: count, dtype: int64
--------------------------------------------------

## 4. Timeliness

In [727]:
df_copy

,Order_ID,Order_Date,Order_Priority,Customer_ID,Customer_Name,Industry_name,Customer_Segment,Province,Region,Channel,...,Product_Category,Product_Sub-Category,Product_Name,Sales,Quantity,Unit_Price,Discount,Profit,Returned_Reason,Age_Group
0,HC-2011-103800,1/4/24,Medium,DP-13000,Darren Tran,Thiết bị gia dụng,Consumer,Hồ Chí Minh,Miền Đông Nam Bộ,Store,...,Hàng điện lạnh,Tủ lạnh,"Message Book, Wirebound, Four 5 1/2"" X 4"" Form...",16.448,2.0,8.224,0.2,5.5512,No reason,>=55
1,NA-2011-112326,2024.01.05,Medium,PO-19195,Phillina Ober,Thiết bị gia dụng,Home Office,Nghệ An,Miền Trung,Online,...,Hàng điện lạnh,Máy điều hòa,MÁY LẠNH DAIKIN FTKC60NVMV-BBB,11.784,3.0,3.928,0.2,4.2717,NaN,35-44
2,NA-2011-112326,1/5/24,Low,PO-19195,Phillina Ober,Thiết bị gia dụng,Home Office,Nghệ An,Miền Trung,Online,...,Hàng điện lạnh,Máy điều hòa,MÁY LẠNH LG V13BPB,272.736,3.0,90.912,0.2,-64.7748,NaN,>=55
3,NA-2011-112326,1/5/24,Low,PO-19195,Phillina Ober,Thiết bị gia dụng,Home Office,Nghệ An,Miền Đông Nam Bộ,Online,...,Hàng điện lạnh,Máy giặt,GBC Standard Plastic Binding Systems Combs,3.540,2.0,1.770,0.8,-5.4870,NaN,45-54
4,TN-2011-141817,1/6/24,Medium,MB-18085,Trần Nhiễm,Thiết bị gia dụng,Consumer,Tây Ninh,Miền Đông Nam Bộ,Store,...,Hàng điện lạnh,Máy giặt,Avery Hi-Liter EverBold Pen Style Fluorescent ...,19.536,3.0,6.512,0.2,4.8840,NaN,25-34
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
498,HT-2011-127166,5/21/24,Medium,KH-16360,Trần Đức,Thiết bị gia dụng,Consumer,Hà Tỉnh,Miền Trung,Agent,...,Hàng điện lạnh,Tủ lạnh,"Adams Telephone Message Books, 5 1/4” x 11”",4.832,1.0,4.832,0.2,1.6308,NaN,>=55
499,HT-2011-127166,5/21/24,Low,KH-16360,Trần Đức,Thiết bị gia dụng,Consumer,Hà Tỉnh,Miền Trung,Agent,...,Hàng điện lạnh,Máy giặt,Ibico Plastic Spiral Binding Combs,18.240,3.0,6.080,0.8,-31.0080,NaN,>=55
500,HT-2011-127166,5/21/24,Low,KH-16360,Trần Đức,Thiết bị gia dụng,Consumer,Hà Tỉnh,Miền Trung,Agent,...,Hàng điện lạnh,Máy giặt,Ibico Plastic Spiral Binding Combs,18.240,3.0,6.080,0.8,-31.0080,NaN,>=55
501,HC-2011-130673,5/20/24,Low,MC-17590,Nguyễn Thị Thu Hường,Thiết bị gia dụng,Corporate,Hồ Chí Minh,Miền Đông Nam Bộ,Agent,...,Hàng điện lạnh,Máy điều hòa,Rogers Profile Extra Capacity Máy điều hòa Tub,66.960,5.0,13.392,0.2,-13.3920,NaN,25-34
502,HC-2011-113768,5/13/24,Medium,AH-10030,Trương Thanh Vân,Thiết bị gia dụng,Corporate,Hồ Chí Minh,Miền Đông Nam Bộ,Agent,...,Nội thất,Ghế,"Iceberg Nesting Folding Chair, 19w x 6d x 43h",279.456,6.0,46.576,0.2,20.9592,NaN,18-24

In [728]:
# Create new column and convert date to datetime, if error --> NaT
df_copy['order_date_original'] = df_copy['Order_Date']
df_copy['order_date_cleaned'] = df_copy['Order_Date']
df_copy['Order_Date'] = pd.to_datetime(df_copy['Order_Date'], errors='coerce')

<ipython-input-728-2d69014c93f0>:4: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  df_copy['Order_Date'] = pd.to_datetime(df_copy['Order_Date'], errors='coerce')

In [729]:
df_copy[df_copy['Order_Date'].isna()][['order_date_original']]

    order_date_original
276          2024-03-32
277          2024-03-32

In [730]:
df_copy['order_date_cleaned'] = df_copy['order_date_cleaned'].astype(str)
df_copy['order_date_cleaned'] = df_copy['order_date_cleaned'].str.replace(r"[./]", "-", regex=True)
df_copy['order_date_cleaned'] = df_copy['order_date_cleaned'].replace("2024-03-32", "2024-03-31")
df_copy['order_date_cleaned'] = df_copy['order_date_cleaned'].replace("15-05-23", "2023-05-15")
df_copy['order_date_cleaned'] = pd.to_datetime(df_copy['order_date_cleaned'], format="mixed", dayfirst=True).dt.strftime('%Y-%m-%d')
df_copy

,Order_ID,Order_Date,Order_Priority,Customer_ID,Customer_Name,Industry_name,Customer_Segment,Province,Region,Channel,...,Product_Name,Sales,Quantity,Unit_Price,Discount,Profit,Returned_Reason,Age_Group,order_date_original,order_date_cleaned
0,HC-2011-103800,2024-01-04,Medium,DP-13000,Darren Tran,Thiết bị gia dụng,Consumer,Hồ Chí Minh,Miền Đông Nam Bộ,Store,...,"Message Book, Wirebound, Four 5 1/2"" X 4"" Form...",16.448,2.0,8.224,0.2,5.5512,No reason,>=55,1/4/24,2024-04-01
1,NA-2011-112326,2024-01-05,Medium,PO-19195,Phillina Ober,Thiết bị gia dụng,Home Office,Nghệ An,Miền Trung,Online,...,MÁY LẠNH DAIKIN FTKC60NVMV-BBB,11.784,3.0,3.928,0.2,4.2717,NaN,35-44,2024.01.05,2024-01-05
2,NA-2011-112326,2024-01-05,Low,PO-19195,Phillina Ober,Thiết bị gia dụng,Home Office,Nghệ An,Miền Trung,Online,...,MÁY LẠNH LG V13BPB,272.736,3.0,90.912,0.2,-64.7748,NaN,>=55,1/5/24,2024-05-01
3,NA-2011-112326,2024-01-05,Low,PO-19195,Phillina Ober,Thiết bị gia dụng,Home Office,Nghệ An,Miền Đông Nam Bộ,Online,...,GBC Standard Plastic Binding Systems Combs,3.540,2.0,1.770,0.8,-5.4870,NaN,45-54,1/5/24,2024-05-01
4,TN-2011-141817,2024-01-06,Medium,MB-18085,Trần Nhiễm,Thiết bị gia dụng,Consumer,Tây Ninh,Miền Đông Nam Bộ,Store,...,Avery Hi-Liter EverBold Pen Style Fluorescent ...,19.536,3.0,6.512,0.2,4.8840,NaN,25-34,1/6/24,2024-06-01
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
498,HT-2011-127166,2024-05-21,Medium,KH-16360,Trần Đức,Thiết bị gia dụng,Consumer,Hà Tỉnh,Miền Trung,Agent,...,"Adams Telephone Message Books, 5 1/4” x 11”",4.832,1.0,4.832,0.2,1.6308,NaN,>=55,5/21/24,2024-05-21
499,HT-2011-127166,2024-05-21,Low,KH-16360,Trần Đức,Thiết bị gia dụng,Consumer,Hà Tỉnh,Miền Trung,Agent,...,Ibico Plastic Spiral Binding Combs,18.240,3.0,6.080,0.8,-31.0080,NaN,>=55,5/21/24,2024-05-21
500,HT-2011-127166,2024-05-21,Low,KH-16360,Trần Đức,Thiết bị gia dụng,Consumer,Hà Tỉnh,Miền Trung,Agent,...,Ibico Plastic Spiral Binding Combs,18.240,3.0,6.080,0.8,-31.0080,NaN,>=55,5/21/24,2024-05-21
501,HC-2011-130673,2024-05-20,Low,MC-17590,Nguyễn Thị Thu Hường,Thiết bị gia dụng,Corporate,Hồ Chí Minh,Miền Đông Nam Bộ,Agent,...,Rogers Profile Extra Capacity Máy điều hòa Tub,66.960,5.0,13.392,0.2,-13.3920,NaN,25-34,5/20/24,2024-05-20
502,HC-2011-113768,2024-05-13,Medium,AH-10030,Trương Thanh Vân,Thiết bị gia dụng,Corporate,Hồ Chí Minh,Miền Đông Nam Bộ,Agent,...,"Iceberg Nesting Folding Chair, 19w x 6d x 43h",279.456,6.0,46.576,0.2,20.9592,NaN,18-24,5/13/24,2024-05-13

In [731]:
df_copy[df_copy['Order_Date'].isna()][['order_date_cleaned']]

    order_date_cleaned
276         2024-03-31
277         2024-03-31

In [732]:
df_copy['Order_Date'].fillna(df_copy['order_date_cleaned'], inplace=True)

<ipython-input-732-14a012ccca66>:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df_copy['Order_Date'].fillna(df_copy['order_date_cleaned'], inplace=True)

In [733]:
df_copy[df_copy['Order_Date'].isna()][['order_date_original']]

Empty DataFrame
Columns: [order_date_original]
Index: []

## 5. Uniqueness

- Identify Duplicates
- Drop Duplicates
- Verify After Dropping Duplicates

In [734]:
# 5.1 Check for duplicate rows in the entire DataFrame
df_copy.duplicated().sum()

np.int64(3)

In [735]:
# Display duplicate rows:
df_copy[df_copy.duplicated()]

,Order_ID,Order_Date,Order_Priority,Customer_ID,Customer_Name,Industry_name,Customer_Segment,Province,Region,Channel,...,Product_Name,Sales,Quantity,Unit_Price,Discount,Profit,Returned_Reason,Age_Group,order_date_original,order_date_cleaned
500,HT-2011-127166,2024-05-21,Low,KH-16360,Trần Đức,Thiết bị gia dụng,Consumer,Hà Tỉnh,Miền Trung,Agent,...,Ibico Plastic Spiral Binding Combs,18.240,3.0,6.080,0.8,-31.0080,NaN,>=55,5/21/24,2024-05-21
501,HC-2011-130673,2024-05-20,Low,MC-17590,Nguyễn Thị Thu Hường,Thiết bị gia dụng,Corporate,Hồ Chí Minh,Miền Đông Nam Bộ,Agent,...,Rogers Profile Extra Capacity Máy điều hòa Tub,66.960,5.0,13.392,0.2,-13.3920,NaN,25-34,5/20/24,2024-05-20
502,HC-2011-113768,2024-05-13,Medium,AH-10030,Trương Thanh Vân,Thiết bị gia dụng,Corporate,Hồ Chí Minh,Miền Đông Nam Bộ,Agent,...,"Iceberg Nesting Folding Chair, 19w x 6d x 43h",279.456,6.0,46.576,0.2,20.9592,NaN,18-24,5/13/24,2024-05-13

In [736]:
# Remove all duplicate rows, keeping the first occurrence:
df_copy.drop_duplicates(inplace=True)
# Drop duplicates in a specific column (keeping the first occurrence):
# df_copy.drop_duplicates(subset=['column_name'], inplace=True)

In [737]:
# Check for duplicates in a specific column:
# df_copy['column_name'].duplicated().sum()

In [738]:
df_copy.info()

<class 'pandas.core.frame.DataFrame'>
Index: 495 entries, 0 to 499
Data columns (total 23 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   Order_ID              495 non-null    object
 1   Order_Date            495 non-null    datetime64[ns]
 2   Order_Priority        495 non-null    object
 3   Customer_ID           495 non-null    object
 4   Customer_Name         495 non-null    object
 5   Industry_name         495 non-null    object
 6   Customer_Segment      495 non-null    object
 7   Province              495 non-null    object
 8   Region                495 non-null    object
 9   Channel               495 non-null    object
 10  Product_ID            495 non-null    object
 11  Product_Category      495 non-null    object
 12  Product_Sub-Category  495 non-null    object
 13  Product_Name          495 non-null    object
 14  Sales                 495 non-null    float64
 15  Quantity              495 non-null    float64
 16  Unit_Price            495 non-null    float64
 17  Discount              495 non-null    float64
 18  Profit                495 non-null    float64
 19  Returned_Reason       6 non-null      object
 20  Age_Group             495 non-null    object
 21  order_date_original   495 non-null    object
 22  order_date_cleaned    495 non-null    object
dtypes: datetime64[ns](1), float64(5), object(17)
memory usage: 92.8+ KB

In [739]:
df_copy.describe()

,Order_Date,Sales,Quantity,Unit_Price,Discount,Profit
count,495,495.000000,495.000000,495.000000,495.000000,495.000000
mean,2024-03-20 18:37:05.454545408,237.004095,3.779798,58.315556,0.143333,18.229572
min,2023-05-15 00:00:00,0.852000,1.000000,0.360000,0.000000,-1811.078400
25%,2024-02-26 12:00:00,16.600000,2.000000,5.184000,0.000000,2.310400
50%,2024-03-25 00:00:00,46.864000,3.000000,13.350000,0.000000,7.264000
75%,2024-04-19 00:00:00,169.105000,5.000000,55.490000,0.200000,24.095200
max,2024-12-05 00:00:00,22638.480000,14.000000,3773.080000,0.800000,1276.487100
std,NaN,1087.341781,2.242846,187.734192,0.196621,137.865054