# Structure, Unstructured and Semi-structured data

# 0. Import library & Install libary

In [ ]:
# import libary
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [3]:
# Install libary
# ! pip install <library_name>
!pip install gdown

Requirement already satisfied: gdown in /usr/local/lib/python3.11/dist-packages (5.2.0)
Requirement already satisfied: beautifulsoup4 in /usr/local/lib/python3.11/dist-packages (from gdown) (4.13.3)
Requirement already satisfied: filelock in /usr/local/lib/python3.11/dist-packages (from gdown) (3.17.0)
Requirement already satisfied: requests[socks] in /usr/local/lib/python3.11/dist-packages (from gdown) (2.32.3)
Requirement already satisfied: tqdm in /usr/local/lib/python3.11/dist-packages (from gdown) (4.67.1)
Requirement already satisfied: soupsieve>1.2 in /usr/local/lib/python3.11/dist-packages (from beautifulsoup4->gdown) (2.6)
Requirement already satisfied: typing-extensions>=4.0.0 in /usr/local/lib/python3.11/dist-packages (from beautifulsoup4->gdown) (4.12.2)
Requirement already satisfied: charset-normalizer<4,>=2 in /usr/local/lib/python3.11/dist-packages (from requests[socks]->gdown) (3.4.1)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.11/dist-packages (from requests[socks]->gdown) (3.10)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.11/dist-packages (from requests[socks]->gdown) (2.3.0)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.11/dist-packages (from requests[socks]->gdown) (2025.1.31)
Requirement already satisfied: PySocks!=1.5.7,>=1.5.6 in /usr/local/lib/python3.11/dist-packages (from requests[socks]->gdown) (1.7.1)

#  1. Structured Data

## 1.1 Download the data file using gdown from google drive

In [14]:
# Download data from google drive
import gdown
file_id = "1-1Jg5njURQTRGYOFNH66wZ89x-pSIsHx"
structured_data = "structured_data.csv"
gdown.download(f"https://drive.google.com/uc?id={file_id}", structured_data, quiet=False)

Downloading...
From: https://drive.google.com/uc?id=1-1Jg5njURQTRGYOFNH66wZ89x-pSIsHx
To: /content/structured_data.csv
100%|██████████| 22.7k/22.7k [00:00<00:00, 24.5MB/s]

'structured_data.csv'

## 1.2 Read the CSV file

In [27]:
# Read the csv file using pandas
import pandas as pd

# Load the CSV file into a DataFrame
df_structured_data = pd.read_csv("structured_data.csv")
print(df_structured_data)

      ID           Full Name   Age                    Major   GPA
0      1         Angela Cobb  21.0            Cybersecurity  8.02
1      2  Shawn Castillo Jr.  19.0             Data Science  9.21
2      3         Luis Parker  18.0         Computer Science  9.53
3      4      Morgan Ballard  24.0      Applied Mathematics  6.75
4      5   Patricia Randolph  23.0             Data Science  5.32
..   ...                 ...   ...                      ...   ...
495  496     Nathaniel Young  19.0            Cybersecurity  6.20
496  497     Jennifer Newton  25.0  Artificial Intelligence  7.62
497  498      Dalton Walters  19.0             Data Science  8.57
498  499      Bradley Carson  24.0      Applied Mathematics  9.73
499  500       Darren Austin  21.0  Artificial Intelligence  5.31

[500 rows x 5 columns]

## 1.3 Perform basic operations on structured data

In [16]:
# 1.3.1 Check dataset information
print(df_structured_data.head()) # Show first few rows

   ID           Full Name   Age                Major   GPA
0   1         Angela Cobb  21.0        Cybersecurity  8.02
1   2  Shawn Castillo Jr.  19.0         Data Science  9.21
2   3         Luis Parker  18.0     Computer Science  9.53
3   4      Morgan Ballard  24.0  Applied Mathematics  6.75
4   5   Patricia Randolph  23.0         Data Science  5.32

In [17]:
print(df_structured_data.tail()) # Display the last few rows

      ID        Full Name   Age                    Major   GPA
495  496  Nathaniel Young  19.0            Cybersecurity  6.20
496  497  Jennifer Newton  25.0  Artificial Intelligence  7.62
497  498   Dalton Walters  19.0             Data Science  8.57
498  499   Bradley Carson  24.0      Applied Mathematics  9.73
499  500    Darren Austin  21.0  Artificial Intelligence  5.31

In [18]:
print(df_structured_data.info())  # Check column names and data types

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 500 entries, 0 to 499
Data columns (total 5 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   ID         500 non-null    int64
 1   Full Name  500 non-null    object
 2   Age        497 non-null    float64
 3   Major      500 non-null    object
 4   GPA        497 non-null    float64
dtypes: float64(2), int64(1), object(2)
memory usage: 19.7+ KB
None

In [19]:
print(df_structured_data.describe())  # Show summary statistics

               ID         Age         GPA
count  500.000000  497.000000  497.000000
mean   250.500000   21.462777    7.390221
std    144.481833    2.260086    1.446111
min      1.000000   18.000000    5.010000
25%    125.750000   20.000000    6.140000
50%    250.500000   21.000000    7.360000
75%    375.250000   23.000000    8.610000
max    500.000000   25.000000    9.990000

In [20]:
print(df_structured_data.shape)  # Print the number of rows and columns

(500, 5)

In [21]:
# 1.3.2 Select
df_structured_data['Major']  # Select a single column

0                Cybersecurity
1                 Data Science
2             Computer Science
3          Applied Mathematics
4                 Data Science
                ...
495              Cybersecurity
496    Artificial Intelligence
497               Data Science
498        Applied Mathematics
499    Artificial Intelligence
Name: Major, Length: 500, dtype: object

In [22]:
df_structured_data[['ID', 'Full Name', 'Major']]  # Select multiple columns

      ID           Full Name                    Major
0      1         Angela Cobb            Cybersecurity
1      2  Shawn Castillo Jr.             Data Science
2      3         Luis Parker         Computer Science
3      4      Morgan Ballard      Applied Mathematics
4      5   Patricia Randolph             Data Science
..   ...                 ...                      ...
495  496     Nathaniel Young            Cybersecurity
496  497     Jennifer Newton  Artificial Intelligence
497  498      Dalton Walters             Data Science
498  499      Bradley Carson      Applied Mathematics
499  500       Darren Austin  Artificial Intelligence

[500 rows x 3 columns]

In [23]:
df_structured_data.iloc[0]  # Select the first row

ID                       1
Full Name      Angela Cobb
Age                   21.0
Major        Cybersecurity
GPA                   8.02
Name: 0, dtype: object

In [24]:
# 1.3.3 Handle missing values
df_structured_data.isnull().sum()  # Count missing values per column

ID           0
Full Name    0
Age          3
Major        0
GPA          3
dtype: int64

In [30]:
df_structured_data[df_structured_data.isna().any(axis=1)] # Show NAN Rows

      ID        Full Name   Age                 Major   GPA
15    16      David Smith  23.0   Information Systems   NaN
40    41     Willie Smith  24.0  Software Engineering   NaN
126  127      Cindy Brown  20.0  Software Engineering   NaN
130  131  Elizabeth Moore   NaN   Information Systems  9.41
149  150  Stephen Ramirez   NaN          Data Science  9.75
179  180     Jackie Lewis   NaN          Data Science  7.03

In [31]:
df_structured_data_copy1 = df_structured_data.copy()
df_structured_data_copy1.dropna(inplace=True)  # Remove rows with missing values

In [32]:
df_structured_data_copy1

      ID           Full Name   Age                    Major   GPA
0      1         Angela Cobb  21.0            Cybersecurity  8.02
1      2  Shawn Castillo Jr.  19.0             Data Science  9.21
2      3         Luis Parker  18.0         Computer Science  9.53
3      4      Morgan Ballard  24.0      Applied Mathematics  6.75
4      5   Patricia Randolph  23.0             Data Science  5.32
..   ...                 ...   ...                      ...   ...
495  496     Nathaniel Young  19.0            Cybersecurity  6.20
496  497     Jennifer Newton  25.0  Artificial Intelligence  7.62
497  498      Dalton Walters  19.0             Data Science  8.57
498  499      Bradley Carson  24.0      Applied Mathematics  9.73
499  500       Darren Austin  21.0  Artificial Intelligence  5.31

[494 rows x 5 columns]

In [34]:
df_structured_data_copy1[df_structured_data_copy1['ID'] == 16]

Empty DataFrame
Columns: [ID, Full Name, Age, Major, GPA]
Index: []

In [35]:
df_structured_data_copy2 = df_structured_data.copy()
df_structured_data_copy2.fillna(0, inplace=True)  # Replace missing values with 0

In [36]:
df_structured_data_copy2[df_structured_data_copy2['ID'] == 16]

    ID    Full Name   Age                Major  GPA
15  16  David Smith  23.0  Information Systems  0.0

In [38]:
df_structured_data_copy3 = df_structured_data.copy()
df_structured_data_copy3['Age'].fillna(df_structured_data_copy3['Age'].mean(), inplace=True) # Fill missing values with the column mean

<ipython-input-38-fed2f06a0c72>:2: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df_structured_data_copy3['Age'].fillna(df_structured_data_copy3['Age'].mean(), inplace=True) # Fill missing values with the column mean

In [39]:
df_structured_data_copy3[df_structured_data_copy3['ID'] == 131]

      ID        Full Name        Age                Major   GPA
130  131  Elizabeth Moore  21.462777  Information Systems  9.41

In [40]:
df_structured_data_copy4 = df_structured_data.copy()
df_structured_data_copy4["Age"].fillna(18, inplace=True) # Fill specific column with a default value

<ipython-input-40-101e7164d46a>:2: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df_structured_data_copy4["Age"].fillna(18, inplace=True) # Fill specific column with a default value

In [41]:
df_structured_data_copy4[df_structured_data_copy4['ID'] == 131]

      ID        Full Name   Age                Major   GPA
130  131  Elizabeth Moore  18.0  Information Systems  9.41

In [42]:
# 1.3.4 Add, modify, and delete columns
df_structured_data["GPA_4_scales"] = df_structured_data["GPA"] * 4 / 10  # Create a new column

In [43]:
df_structured_data

,ID,Full Name,Age,Major,GPA,GPA_4_scales
0,1,Angela Cobb,21.0,Cybersecurity,8.02,3.208
1,2,Shawn Castillo Jr.,19.0,Data Science,9.21,3.684
2,3,Luis Parker,18.0,Computer Science,9.53,3.812
3,4,Morgan Ballard,24.0,Applied Mathematics,6.75,2.700
4,5,Patricia Randolph,23.0,Data Science,5.32,2.128
...,...,...,...,...,...,...
495,496,Nathaniel Young,19.0,Cybersecurity,6.20,2.480
496,497,Jennifer Newton,25.0,Artificial Intelligence,7.62,3.048
497,498,Dalton Walters,19.0,Data Science,8.57,3.428
498,499,Bradley Carson,24.0,Applied Mathematics,9.73,3.892
499,500,Darren Austin,21.0,Artificial Intelligence,5.31,2.124

In [44]:
df_structured_data.rename(columns={"GPA": "GPA_10_Scale"}, inplace=True) # Rename columns

In [45]:
df_structured_data

,ID,Full Name,Age,Major,GPA_10_Scale,GPA_4_scales
0,1,Angela Cobb,21.0,Cybersecurity,8.02,3.208
1,2,Shawn Castillo Jr.,19.0,Data Science,9.21,3.684
2,3,Luis Parker,18.0,Computer Science,9.53,3.812
3,4,Morgan Ballard,24.0,Applied Mathematics,6.75,2.700
4,5,Patricia Randolph,23.0,Data Science,5.32,2.128
...,...,...,...,...,...,...
495,496,Nathaniel Young,19.0,Cybersecurity,6.20,2.480
496,497,Jennifer Newton,25.0,Artificial Intelligence,7.62,3.048
497,498,Dalton Walters,19.0,Data Science,8.57,3.428
498,499,Bradley Carson,24.0,Applied Mathematics,9.73,3.892
499,500,Darren Austin,21.0,Artificial Intelligence,5.31,2.124

In [47]:
df_structured_data_copy4["Age"] = df_structured_data_copy4["Age"].astype(int) # Convert data types

In [48]:
df_structured_data_copy4.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 500 entries, 0 to 499
Data columns (total 5 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   ID         500 non-null    int64
 1   Full Name  500 non-null    object
 2   Age        500 non-null    int64
 3   Major      500 non-null    object
 4   GPA        497 non-null    float64
dtypes: float64(1), int64(2), object(2)
memory usage: 19.7+ KB

In [49]:
df_structured_data.columns = df_structured_data.columns.str.lower() # Change case of column names

In [50]:
df_structured_data

,id,full name,age,major,gpa_10_scale,gpa_4_scales
0,1,Angela Cobb,21.0,Cybersecurity,8.02,3.208
1,2,Shawn Castillo Jr.,19.0,Data Science,9.21,3.684
2,3,Luis Parker,18.0,Computer Science,9.53,3.812
3,4,Morgan Ballard,24.0,Applied Mathematics,6.75,2.700
4,5,Patricia Randolph,23.0,Data Science,5.32,2.128
...,...,...,...,...,...,...
495,496,Nathaniel Young,19.0,Cybersecurity,6.20,2.480
496,497,Jennifer Newton,25.0,Artificial Intelligence,7.62,3.048
497,498,Dalton Walters,19.0,Data Science,8.57,3.428
498,499,Bradley Carson,24.0,Applied Mathematics,9.73,3.892
499,500,Darren Austin,21.0,Artificial Intelligence,5.31,2.124

In [52]:
df_structured_data.columns = df_structured_data.columns.str.upper() # Change case of column names

In [53]:
df_structured_data

,ID,FULL NAME,AGE,MAJOR,GPA_10_SCALE,GPA_4_SCALES
0,1,Angela Cobb,21.0,Cybersecurity,8.02,3.208
1,2,Shawn Castillo Jr.,19.0,Data Science,9.21,3.684
2,3,Luis Parker,18.0,Computer Science,9.53,3.812
3,4,Morgan Ballard,24.0,Applied Mathematics,6.75,2.700
4,5,Patricia Randolph,23.0,Data Science,5.32,2.128
...,...,...,...,...,...,...
495,496,Nathaniel Young,19.0,Cybersecurity,6.20,2.480
496,497,Jennifer Newton,25.0,Artificial Intelligence,7.62,3.048
497,498,Dalton Walters,19.0,Data Science,8.57,3.428
498,499,Bradley Carson,24.0,Applied Mathematics,9.73,3.892
499,500,Darren Austin,21.0,Artificial Intelligence,5.31,2.124

In [54]:
df_structured_data.columns = df_structured_data.columns.str.title()  # Capitalize first letter of each word

In [55]:
df_structured_data

,Id,Full Name,Age,Major,Gpa_10_Scale,Gpa_4_Scales
0,1,Angela Cobb,21.0,Cybersecurity,8.02,3.208
1,2,Shawn Castillo Jr.,19.0,Data Science,9.21,3.684
2,3,Luis Parker,18.0,Computer Science,9.53,3.812
3,4,Morgan Ballard,24.0,Applied Mathematics,6.75,2.700
4,5,Patricia Randolph,23.0,Data Science,5.32,2.128
...,...,...,...,...,...,...
495,496,Nathaniel Young,19.0,Cybersecurity,6.20,2.480
496,497,Jennifer Newton,25.0,Artificial Intelligence,7.62,3.048
497,498,Dalton Walters,19.0,Data Science,8.57,3.428
498,499,Bradley Carson,24.0,Applied Mathematics,9.73,3.892
499,500,Darren Austin,21.0,Artificial Intelligence,5.31,2.124

In [56]:
df_structured_data['Full Name'] = df_structured_data['Full Name'].str.lower() # Change case of column value

In [57]:
df_structured_data

,Id,Full Name,Age,Major,Gpa_10_Scale,Gpa_4_Scales
0,1,angela cobb,21.0,Cybersecurity,8.02,3.208
1,2,shawn castillo jr.,19.0,Data Science,9.21,3.684
2,3,luis parker,18.0,Computer Science,9.53,3.812
3,4,morgan ballard,24.0,Applied Mathematics,6.75,2.700
4,5,patricia randolph,23.0,Data Science,5.32,2.128
...,...,...,...,...,...,...
495,496,nathaniel young,19.0,Cybersecurity,6.20,2.480
496,497,jennifer newton,25.0,Artificial Intelligence,7.62,3.048
497,498,dalton walters,19.0,Data Science,8.57,3.428
498,499,bradley carson,24.0,Applied Mathematics,9.73,3.892
499,500,darren austin,21.0,Artificial Intelligence,5.31,2.124

In [58]:
df_structured_data['Full Name'] = df_structured_data['Full Name'].str.upper() # Change case of column value

In [59]:
df_structured_data

,Id,Full Name,Age,Major,Gpa_10_Scale,Gpa_4_Scales
0,1,ANGELA COBB,21.0,Cybersecurity,8.02,3.208
1,2,SHAWN CASTILLO JR.,19.0,Data Science,9.21,3.684
2,3,LUIS PARKER,18.0,Computer Science,9.53,3.812
3,4,MORGAN BALLARD,24.0,Applied Mathematics,6.75,2.700
4,5,PATRICIA RANDOLPH,23.0,Data Science,5.32,2.128
...,...,...,...,...,...,...
495,496,NATHANIEL YOUNG,19.0,Cybersecurity,6.20,2.480
496,497,JENNIFER NEWTON,25.0,Artificial Intelligence,7.62,3.048
497,498,DALTON WALTERS,19.0,Data Science,8.57,3.428
498,499,BRADLEY CARSON,24.0,Applied Mathematics,9.73,3.892
499,500,DARREN AUSTIN,21.0,Artificial Intelligence,5.31,2.124

In [60]:
df_structured_data['Full Name'] = df_structured_data['Full Name'].str.title() # Change case of column value

In [61]:
df_structured_data

,Id,Full Name,Age,Major,Gpa_10_Scale,Gpa_4_Scales
0,1,Angela Cobb,21.0,Cybersecurity,8.02,3.208
1,2,Shawn Castillo Jr.,19.0,Data Science,9.21,3.684
2,3,Luis Parker,18.0,Computer Science,9.53,3.812
3,4,Morgan Ballard,24.0,Applied Mathematics,6.75,2.700
4,5,Patricia Randolph,23.0,Data Science,5.32,2.128
...,...,...,...,...,...,...
495,496,Nathaniel Young,19.0,Cybersecurity,6.20,2.480
496,497,Jennifer Newton,25.0,Artificial Intelligence,7.62,3.048
497,498,Dalton Walters,19.0,Data Science,8.57,3.428
498,499,Bradley Carson,24.0,Applied Mathematics,9.73,3.892
499,500,Darren Austin,21.0,Artificial Intelligence,5.31,2.124

In [63]:
df_structured_data.drop(columns=['Gpa_4_Scales'], inplace=True)  # Remove a column

In [64]:
df_structured_data

      Id           Full Name   Age                    Major  Gpa_10_Scale
0      1         Angela Cobb  21.0            Cybersecurity          8.02
1      2  Shawn Castillo Jr.  19.0             Data Science          9.21
2      3         Luis Parker  18.0         Computer Science          9.53
3      4      Morgan Ballard  24.0      Applied Mathematics          6.75
4      5   Patricia Randolph  23.0             Data Science          5.32
..   ...                 ...   ...                      ...           ...
495  496     Nathaniel Young  19.0            Cybersecurity          6.20
496  497     Jennifer Newton  25.0  Artificial Intelligence          7.62
497  498      Dalton Walters  19.0             Data Science          8.57
498  499      Bradley Carson  24.0      Applied Mathematics          9.73
499  500       Darren Austin  21.0  Artificial Intelligence          5.31

[500 rows x 5 columns]

In [65]:
# 1.3.5 Filter & Sort Data
# Filter students with GPA above 8
df_gpa_greater8 = df_structured_data[df_structured_data['Gpa_10_Scale'] > 8.00]  # Filter rows where 'Gpa_10_Scale' > 8.00
print(df_gpa_greater8)

      Id           Full Name   Age                 Major  Gpa_10_Scale
0      1         Angela Cobb  21.0         Cybersecurity          8.02
1      2  Shawn Castillo Jr.  19.0          Data Science          9.21
2      3         Luis Parker  18.0      Computer Science          9.53
7      8           Amy Price  21.0   Applied Mathematics          8.44
10    11    Elizabeth Phelps  19.0   Applied Mathematics          8.68
..   ...                 ...   ...                   ...           ...
490  491        John Baldwin  20.0          Data Science          9.19
492  493        Andrea Jones  24.0         Cybersecurity          8.51
494  495        Sarah Mendez  19.0  Software Engineering          8.99
497  498      Dalton Walters  19.0          Data Science          8.57
498  499      Bradley Carson  24.0   Applied Mathematics          9.73

[182 rows x 5 columns]

In [67]:
# Sort by GPA in descending order
df_structured_data_sorted = df_structured_data.sort_values(by="Gpa_10_Scale", ascending=False)
print(df_structured_data_sorted)

      Id          Full Name   Age                    Major  Gpa_10_Scale
145  146       Derrick Diaz  20.0         Computer Science          9.99
477  478      Stephen Jones  18.0  Artificial Intelligence          9.97
250  251    Lauren Mcknight  22.0            Cybersecurity          9.97
176  177       Kevin Peters  21.0             Data Science          9.97
180  181     Thomas Nichols  22.0      Information Systems          9.96
..   ...                ...   ...                      ...           ...
63    64  Elizabeth Salazar  22.0         Computer Science          5.03
418  419        Katie Meyer  19.0  Artificial Intelligence          5.01
15    16        David Smith  23.0      Information Systems           NaN
40    41       Willie Smith  24.0     Software Engineering           NaN
126  127        Cindy Brown  20.0     Software Engineering           NaN

[500 rows x 5 columns]

In [69]:
# 1.3.6 Grouping & Aggregation
# Find average GPA per major
df_structured_data.groupby("Major")["Gpa_10_Scale"].mean()

Major
Applied Mathematics        7.509683
Artificial Intelligence    7.509600
Computer Science           7.461385
Cybersecurity              7.329444
Data Science               7.503026
Information Systems        7.391646
Software Engineering       7.010896
Name: Gpa_10_Scale, dtype: float64

In [70]:

# Count students per major
df_structured_data["Major"].value_counts()

Major
Information Systems        80
Data Science               76
Artificial Intelligence    75
Cybersecurity              72
Software Engineering       69
Computer Science           65
Applied Mathematics        63
Name: count, dtype: int64

In [73]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [76]:


# 1.3.7
save_path = "/content/drive/MyDrive/HCMUS/Intro2DS/Lab/Lab01/"

# Save to CSV
df_gpa_greater8.to_csv(save_path + "df_gpa_greater8.csv", index=False)


# Save to Excel
df_gpa_greater8.to_excel(save_path + "df_gpa_greater8.xlsx", index=False)

#  2. Semi-structured Data

## 2.1 Download data from google drive

In [77]:
# Download data from google drive
import gdown
file_id1 = "1uS3CPAWbmfQT5ec6Hp_3p_OfTVpAjHVJ"
semistructured_data = "semi_structured.json"
gdown.download(f"https://drive.google.com/uc?id={file_id1}", semistructured_data, quiet=False)

Downloading...
From: https://drive.google.com/uc?id=1uS3CPAWbmfQT5ec6Hp_3p_OfTVpAjHVJ
To: /content/semi_structured.json
100%|██████████| 2.33k/2.33k [00:00<00:00, 4.52MB/s]

'semi_structured.json'

## 2.2 Read data

In [78]:
import json

with open("semi_structured.json", "r", encoding="utf-8") as file:
    data = json.load(file)

## 2.3 Perform basic operations on structured data

### 2.3.1 Retrieve specific information

In [79]:
# Get the list of all students:
students = data["students"]
students

[{'student_id': 'S101',
  'name': 'Alice Johnson',
  'age': 20,
  'GPA': 3.8,
  'contact': {'email': 'alice@example.com', 'phone': '123-456-7890'},
  'subjects': [{'name': 'Math', 'score': 85},
   {'name': 'Physics', 'score': 90}]},
 {'student_id': 'S102',
  'name': 'Bob Smith',
  'age': 21,
  'GPA': 3.5,
  'contact': {'email': 'bob@example.com'},
  'subjects': [{'name': 'Math', 'score': 78},
   {'name': 'Chemistry', 'score': 82},
   {'name': 'English', 'score': 88}]},
 {'student_id': 'S103',
  'name': 'Charlie Brown',
  'age': 19,
  'GPA': 3.9,
  'subjects': [{'name': 'Computer Science', 'score': 92},
   {'name': 'Math', 'score': 88}]},
 {'student_id': 'S104',
  'name': 'David Williams',
  'age': 22,
  'GPA': 3.6,
  'contact': {'email': 'david@example.com', 'phone': '987-654-3210'},
  'subjects': [{'name': 'Biology', 'score': 80},
   {'name': 'Physics', 'score': 85},
   {'name': 'Math', 'score': 82}]},
 {'student_id': 'S105',
  'name': 'Emma Davis',
  'age': 20,
  'GPA': 3.7,
  'contact': {'email': 'emma@example.com'},
  'subjects': [{'name': 'History', 'score': 88},
   {'name': 'English', 'score': 90}]},
 {'student_id': 'S106',
  'name': 'Frank Miller',
  'age': 23,
  'GPA': 3.4,
  'subjects': [{'name': 'Economics', 'score': 76},
   {'name': 'Statistics', 'score': 80},
   {'name': 'Math', 'score': 79}]},
 {'student_id': 'S107',
  'name': 'Grace Wilson',
  'age': 19,
  'GPA': 3.9,
  'contact': {'email': 'grace@example.com', 'phone': '456-789-0123'},
  'subjects': [{'name': 'Computer Science', 'score': 94},
   {'name': 'Math', 'score': 90},
   {'name': 'Physics', 'score': 91}]}]

In [81]:
# Get the names of all students:
student_names = [student["name"] for student in students]
student_names

['Alice Johnson',
 'Bob Smith',
 'Charlie Brown',
 'David Williams',
 'Emma Davis',
 'Frank Miller',
 'Grace Wilson']

In [82]:
# Get the scores of a specific student
alice_scores = [s["subjects"] for s in students if s["name"] == "Alice Johnson"]
alice_scores

[[{'name': 'Math', 'score': 85}, {'name': 'Physics', 'score': 90}]]

### 2.3.2 Add new data

In [83]:
new_student = {
    "student_id": "S108",
    "name": "Henry Clark",
    "age": 21,
    "GPA": 3.6,
    "subjects": [
        {"name": "Math", "score": 85},
        {"name": "Computer Science", "score": 92}
    ]
}
students.append(new_student)
students

[{'student_id': 'S101',
  'name': 'Alice Johnson',
  'age': 20,
  'GPA': 3.8,
  'contact': {'email': 'alice@example.com', 'phone': '123-456-7890'},
  'subjects': [{'name': 'Math', 'score': 85},
   {'name': 'Physics', 'score': 90}]},
 {'student_id': 'S102',
  'name': 'Bob Smith',
  'age': 21,
  'GPA': 3.5,
  'contact': {'email': 'bob@example.com'},
  'subjects': [{'name': 'Math', 'score': 78},
   {'name': 'Chemistry', 'score': 82},
   {'name': 'English', 'score': 88}]},
 {'student_id': 'S103',
  'name': 'Charlie Brown',
  'age': 19,
  'GPA': 3.9,
  'subjects': [{'name': 'Computer Science', 'score': 92},
   {'name': 'Math', 'score': 88}]},
 {'student_id': 'S104',
  'name': 'David Williams',
  'age': 22,
  'GPA': 3.6,
  'contact': {'email': 'david@example.com', 'phone': '987-654-3210'},
  'subjects': [{'name': 'Biology', 'score': 80},
   {'name': 'Physics', 'score': 85},
   {'name': 'Math', 'score': 82}]},
 {'student_id': 'S105',
  'name': 'Emma Davis',
  'age': 20,
  'GPA': 3.7,
  'contact': {'email': 'emma@example.com'},
  'subjects': [{'name': 'History', 'score': 88},
   {'name': 'English', 'score': 90}]},
 {'student_id': 'S106',
  'name': 'Frank Miller',
  'age': 23,
  'GPA': 3.4,
  'subjects': [{'name': 'Economics', 'score': 76},
   {'name': 'Statistics', 'score': 80},
   {'name': 'Math', 'score': 79}]},
 {'student_id': 'S107',
  'name': 'Grace Wilson',
  'age': 19,
  'GPA': 3.9,
  'contact': {'email': 'grace@example.com', 'phone': '456-789-0123'},
  'subjects': [{'name': 'Computer Science', 'score': 94},
   {'name': 'Math', 'score': 90},
   {'name': 'Physics', 'score': 91}]},
 {'student_id': 'S108',
  'name': 'Henry Clark',
  'age': 21,
  'GPA': 3.6,
  'subjects': [{'name': 'Math', 'score': 85},
   {'name': 'Computer Science', 'score': 92}]}]

### 2.3.3 Update existing information

In [86]:
# <!-- Update the GPA of student S102 (Bob Smith): -->
for student in students:
    if student["student_id"] == "S102":
        student["GPA"] = 3.8
        print(student)

{'student_id': 'S102', 'name': 'Bob Smith', 'age': 21, 'GPA': 3.8, 'contact': {'email': 'bob@example.com'}, 'subjects': [{'name': 'Math', 'score': 78}, {'name': 'Chemistry', 'score': 82}, {'name': 'English', 'score': 88}]}

### 2.3.4 Delete data

In [87]:
students = [s for s in students if s["student_id"] != "S103"]
students

[{'student_id': 'S101',
  'name': 'Alice Johnson',
  'age': 20,
  'GPA': 3.8,
  'contact': {'email': 'alice@example.com', 'phone': '123-456-7890'},
  'subjects': [{'name': 'Math', 'score': 85},
   {'name': 'Physics', 'score': 90}]},
 {'student_id': 'S102',
  'name': 'Bob Smith',
  'age': 21,
  'GPA': 3.8,
  'contact': {'email': 'bob@example.com'},
  'subjects': [{'name': 'Math', 'score': 78},
   {'name': 'Chemistry', 'score': 82},
   {'name': 'English', 'score': 88}]},
 {'student_id': 'S104',
  'name': 'David Williams',
  'age': 22,
  'GPA': 3.6,
  'contact': {'email': 'david@example.com', 'phone': '987-654-3210'},
  'subjects': [{'name': 'Biology', 'score': 80},
   {'name': 'Physics', 'score': 85},
   {'name': 'Math', 'score': 82}]},
 {'student_id': 'S105',
  'name': 'Emma Davis',
  'age': 20,
  'GPA': 3.7,
  'contact': {'email': 'emma@example.com'},
  'subjects': [{'name': 'History', 'score': 88},
   {'name': 'English', 'score': 90}]},
 {'student_id': 'S106',
  'name': 'Frank Miller',
  'age': 23,
  'GPA': 3.4,
  'subjects': [{'name': 'Economics', 'score': 76},
   {'name': 'Statistics', 'score': 80},
   {'name': 'Math', 'score': 79}]},
 {'student_id': 'S107',
  'name': 'Grace Wilson',
  'age': 19,
  'GPA': 3.9,
  'contact': {'email': 'grace@example.com', 'phone': '456-789-0123'},
  'subjects': [{'name': 'Computer Science', 'score': 94},
   {'name': 'Math', 'score': 90},
   {'name': 'Physics', 'score': 91}]},
 {'student_id': 'S108',
  'name': 'Henry Clark',
  'age': 21,
  'GPA': 3.6,
  'subjects': [{'name': 'Math', 'score': 85},
   {'name': 'Computer Science', 'score': 92}]}]

### 2.3.5 Save the updated data back to the JSON file

In [89]:
save_path = "/content/drive/MyDrive/HCMUS/Intro2DS/Lab/Lab01//students.json"
# Save JSON file
with open(save_path, "w", encoding="utf-8") as file:
    json.dump({"students": students}, file, indent=4, ensure_ascii=False)

print(f"File saved at: {save_path}")

File saved at: /content/drive/MyDrive/HCMUS/Intro2DS/Lab/Lab01//students.json

# 3. Access Nested Data

In [90]:
# Get all student emails (if available)
emails = [student["contact"]["email"] for student in students if "contact" in student and "email" in student["contact"]]
print(emails)

['alice@example.com', 'bob@example.com', 'david@example.com', 'emma@example.com', 'grace@example.com']

In [91]:
# Get all students and their subjects
for student in students:
    print(f"Student: {student['name']}")
    for subject in student["subjects"]:
        print(f"  - {subject['name']}: {subject['score']}")

Student: Alice Johnson
  - Math: 85
  - Physics: 90
Student: Bob Smith
  - Math: 78
  - Chemistry: 82
  - English: 88
Student: David Williams
  - Biology: 80
  - Physics: 85
  - Math: 82
Student: Emma Davis
  - History: 88
  - English: 90
Student: Frank Miller
  - Economics: 76
  - Statistics: 80
  - Math: 79
Student: Grace Wilson
  - Computer Science: 94
  - Math: 90
  - Physics: 91
Student: Henry Clark
  - Math: 85
  - Computer Science: 92

In [92]:
# Retrieve a specific student’s phone number
alice_phone = next((s["contact"]["phone"] for s in students if s["name"] == "Alice Johnson" and "contact" in s and "phone" in s["contact"]), "No phone available")
print(alice_phone)

123-456-7890

In [93]:
# Find the highest-scoring subject for each student
for student in students:
    best_subject = max(student["subjects"], key=lambda x: x["score"])
    print(f"{student['name']}'s best subject: {best_subject['name']} ({best_subject['score']})")

Alice Johnson's best subject: Physics (90)
Bob Smith's best subject: English (88)
David Williams's best subject: Physics (85)
Emma Davis's best subject: English (90)
Frank Miller's best subject: Statistics (80)
Grace Wilson's best subject: Computer Science (94)
Henry Clark's best subject: Computer Science (92)

# 3. Unstructured data

## 3.1 Download file from google drive

In [94]:
# Download data from google drive
import gdown
file_id2 = "1qfIzXIq_4yTuCzcmbrRCqVzWDKIWv0fA"
unstructured_data = "unstructured_data.txt"
gdown.download(f"https://drive.google.com/uc?id={file_id2}", unstructured_data, quiet=False)

Downloading...
From: https://drive.google.com/uc?id=1qfIzXIq_4yTuCzcmbrRCqVzWDKIWv0fA
To: /content/unstructured_data.txt
100%|██████████| 782/782 [00:00<00:00, 1.42MB/s]

'unstructured_data.txt'

## 3.2 Basic Operations on Unstructured Data in Python

In [95]:
# Read Unstructured Data
with open("unstructured_data.txt", "r", encoding="utf-8") as file:
    data = file.read()

In [96]:
data

'Alice Johnson, 20 years old, GPA 3.8. Email: alice@example.com, Phone: 123-456-7890.\nSubjects: Math (85), Physics (90).\n\nBob Smith, 21 years old, GPA 3.5. Email: bob@example.com.\nSubjects: Math (78), Chemistry (82), English (88).\n\nCharlie Brown, 19 years old, GPA 3.9.\nSubjects: Computer Science (92), Math (88).\n\nDavid Williams, 22 years old, GPA 3.6. Email: david@example.com, Phone: 987-654-3210.\nSubjects: Biology (80), Physics (85), Math (82).\n\nEmma Davis, 20 years old, GPA 3.7. Email: emma@example.com.\nSubjects: History (88), English (90).\n\nFrank Miller, 23 years old, GPA 3.4.\nSubjects: Economics (76), Statistics (80), Math (79).\n\nGrace Wilson, 19 years old, GPA 3.9. Email: grace@example.com, Phone: 456-789-0123.\nSubjects: Computer Science (94), Math (90), Physics (91).'

In [97]:
# Extract Student Names
import re

names = re.findall(r"([A-Z][a-z]+ [A-Z][a-z]+)", data)
print(names)

['Alice Johnson', 'Bob Smith', 'Charlie Brown', 'Computer Science', 'David Williams', 'Emma Davis', 'Frank Miller', 'Grace Wilson', 'Computer Science']

Giải thích từng phần:
re.findall()

Đây là một hàm của module re trong Python, dùng để tìm tất cả các chuỗi khớp với mẫu (pattern) trong data.
Kết quả sẽ là một danh sách (list) chứa các chuỗi phù hợp.

Biểu thức chính quy (r"([A-Z][a-z]+ [A-Z][a-z]+)")

([A-Z][a-z]+ [A-Z][a-z]+): Đây là một nhóm (group) dùng để tìm kiếm các tên đầy đủ có hai chữ, trong đó:
[A-Z] → Chữ cái đầu viết hoa (A-Z).
[a-z]+ → Các chữ cái tiếp theo viết thường (a-z), xuất hiện ít nhất một lần (+).
Khoảng trắng ( ) → Giữa hai từ, yêu cầu cả họ và tên phải có định dạng giống nhau.
[A-Z][a-z]+ → Từ thứ hai cũng phải có chữ cái đầu viết hoa và phần sau viết thường.

In [13]:
# Extract Emails
emails = re.findall(r"[a-zA-Z0-9._%+-]+@[a-zA-Z0-9.-]+\.[a-zA-Z]{2,}", data)
print(emails)

['alice@example.com', 'bob@example.com', 'david@example.com', 'emma@example.com', 'grace@example.com']

✅ [a-zA-Z0-9._%+-]+
Tìm phần tên tài khoản (username) trước dấu @.
Chứa các ký tự:
a-zA-Z0-9 → Chữ cái hoa (A-Z), chữ thường (a-z), số (0-9).
._%+- → Các ký tự đặc biệt hợp lệ trong email (. _ % + -).
+ → Yêu cầu ít nhất một lần xuất hiện.

✅ @
Dấu @ là bắt buộc trong email.

✅ [a-zA-Z0-9.-]+
Tìm phần tên miền (domain) sau @.
Chứa các ký tự:
a-zA-Z0-9 → Chữ cái hoa, chữ thường, số.
. và - → Dấu chấm (.) và dấu gạch ngang (-) hợp lệ trong domain.
+ → Yêu cầu ít nhất một lần xuất hiện.

✅ \.[a-zA-Z]{2,}
Tìm đuôi miền (TLD - Top-Level Domain), như .com, .org, .edu, .vn, ...
\. → Dấu . bắt buộc.
[a-zA-Z]{2,} → Tìm chuỗi gồm ít nhất 2 chữ cái ({2,}), ví dụ: com, net, gov, edu.

In [98]:
# Extract GPAs
gpas = re.findall(r"GPA (\d\.\d)", data)
print(gpas)

['3.8', '3.5', '3.9', '3.6', '3.7', '3.4', '3.9']

In [99]:
# Extract Subject Scores
subjects = re.findall(r"(\w+)\s\((\d+)\)", data)
print(subjects)  # Returns list of tuples (subject, score)

[('Math', '85'), ('Physics', '90'), ('Math', '78'), ('Chemistry', '82'), ('English', '88'), ('Science', '92'), ('Math', '88'), ('Biology', '80'), ('Physics', '85'), ('Math', '82'), ('History', '88'), ('English', '90'), ('Economics', '76'), ('Statistics', '80'), ('Math', '79'), ('Science', '94'), ('Math', '90'), ('Physics', '91')]

✅ (\w+):


* \w+ → Tìm một từ (môn học).
* \w tương đương với [a-zA-Z0-9_] : Bao gồm chữ cái (hoa/thường), số, và dấu gạch dưới _.

* "+" → Yêu cầu ít nhất một ký tự trở lên (có thể là "Math", "Physics", "Biology"…).

* Dấu ngoặc () → Tạo nhóm Group 1, tức là lưu lại tên môn học.

✅ \s
* \s → Đại diện cho khoảng trắng (space), dấu tab hoặc dòng mới (\n).
* Trong ngữ cảnh này, nó dùng để đảm bảo có một khoảng trắng giữa tên môn học và dấu mở ngoặc (.

✅ \((\d+)\)
* \( và \) → Dấu ngoặc tròn () xuất hiện trong dữ liệu, nhưng trong regex, chúng là ký tự đặc biệt, nên cần escape (\) để tìm chính xác dấu ( và ).
* (\d+) → Tìm một hoặc nhiều chữ số (\d+), biểu thị điểm số.
\d tương đương với [0-9] (chỉ nhận số).
* Dấu ngoặc () → Tạo nhóm Group 2, tức là lưu lại điểm số.

## 3.3 Convert Unstructured Data to JSON

In [100]:
students = []
for match in re.finditer(r"([A-Z][a-z]+ [A-Z][a-z]+), (\d+) years old, GPA (\d\.\d).*?Email: ([\w@.]+)?.*?Subjects: (.+?)\.", data, re.DOTALL):
    name, age, gpa, email, subjects_str = match.groups()
    subjects = [{"name": sub.split(" (")[0], "score": int(sub.split(" (")[1][:-1])} for sub in subjects_str.split(", ")]

    student = {
        "name": name,
        "age": int(age),
        "GPA": float(gpa),
        "contact": {"email": email} if email else {},
        "subjects": subjects
    }
    students.append(student)

import json
json_data = json.dumps({"students": students}, indent=4)
print(json_data)

{
    "students": [
        {
            "name": "Alice Johnson",
            "age": 20,
            "GPA": 3.8,
            "contact": {
                "email": "alice@example.com"
            },
            "subjects": [
                {
                    "name": "Math",
                    "score": 85
                },
                {
                    "name": "Physics",
                    "score": 90
                }
            ]
        },
        {
            "name": "Bob Smith",
            "age": 21,
            "GPA": 3.5,
            "contact": {
                "email": "bob@example.com."
            },
            "subjects": [
                {
                    "name": "Math",
                    "score": 78
                },
                {
                    "name": "Chemistry",
                    "score": 82
                },
                {
                    "name": "English",
                    "score": 88
                }
            ]
        },
        {
            "name": "Charlie Brown",
            "age": 19,
            "GPA": 3.9,
            "contact": {
                "email": "david@example.com"
            },
            "subjects": [
                {
                    "name": "Biology",
                    "score": 80
                },
                {
                    "name": "Physics",
                    "score": 85
                },
                {
                    "name": "Math",
                    "score": 82
                }
            ]
        },
        {
            "name": "Emma Davis",
            "age": 20,
            "GPA": 3.7,
            "contact": {
                "email": "emma@example.com."
            },
            "subjects": [
                {
                    "name": "History",
                    "score": 88
                },
                {
                    "name": "English",
                    "score": 90
                }
            ]
        },
        {
            "name": "Frank Miller",
            "age": 23,
            "GPA": 3.4,
            "contact": {
                "email": "grace@example.com"
            },
            "subjects": [
                {
                    "name": "Computer Science",
                    "score": 94
                },
                {
                    "name": "Math",
                    "score": 90
                },
                {
                    "name": "Physics",
                    "score": 91
                }
            ]
        }
    ]
}